# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.AcceptInviteRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :first_name,
    :last_name,
    :password,
    :privacy_accepted,
    :token
  ]

  @type t :: %__MODULE__{
    :first_name => String.t,
    :last_name => String.t,
    :password => String.t,
    :privacy_accepted => boolean(),
    :token => String.t
  }

  def decode(value) do
    value
  end
end

