# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ActivityUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :activityType,
    :assignedTo,
    :contactId,
    :description,
    :dueDate,
    :reminderDate,
    :status,
    :subject
  ]

  @type t :: %__MODULE__{
    :activityType => SimpleBillyAPI.Model.ActivityType.t | nil,
    :assignedTo => String.t | nil,
    :contactId => String.t | nil,
    :description => String.t | nil,
    :dueDate => Date.t | nil,
    :reminderDate => Date.t | nil,
    :status => SimpleBillyAPI.Model.ActivityStatus.t | nil,
    :subject => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:activityType, :struct, SimpleBillyAPI.Model.ActivityType)
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.ActivityStatus)
  end
end

