# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.Address do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :city,
    :company,
    :country,
    :email,
    :name,
    :phone,
    :street,
    :street_number,
    :zip
  ]

  @type t :: %__MODULE__{
    :city => String.t,
    :company => String.t | nil,
    :country => String.t,
    :email => String.t | nil,
    :name => String.t,
    :phone => String.t | nil,
    :street => String.t,
    :street_number => String.t,
    :zip => String.t
  }

  def decode(value) do
    value
  end
end

