# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.AiConfigDto do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :auto_reply,
    :max_tool_calls,
    :model,
    :name,
    :provider,
    :system_prompt,
    :trigger_on
  ]

  @type t :: %__MODULE__{
    :auto_reply => boolean() | nil,
    :max_tool_calls => integer() | nil,
    :model => String.t,
    :name => String.t,
    :provider => String.t,
    :system_prompt => String.t | nil,
    :trigger_on => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

