# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.AiSuggestionRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :instructions,
    :message_body,
    :ticket_id
  ]

  @type t :: %__MODULE__{
    :instructions => String.t | nil,
    :message_body => String.t | nil,
    :ticket_id => String.t
  }

  def decode(value) do
    value
  end
end

