# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.AiSuggestion do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :confidence,
    :reasoning,
    :suggested_priority,
    :suggested_reply,
    :suggested_status,
    :tool_calls
  ]

  @type t :: %__MODULE__{
    :confidence => float(),
    :reasoning => String.t,
    :suggested_priority => String.t | nil,
    :suggested_reply => String.t,
    :suggested_status => String.t | nil,
    :tool_calls => [String.t]
  }

  def decode(value) do
    value
  end
end

