# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.AiWorkerConfig do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :auto_reply,
    :created_at,
    :id,
    :is_active,
    :max_tool_calls,
    :model,
    :name,
    :provider,
    :system_prompt,
    :tenant_id,
    :trigger_on,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :auto_reply => boolean(),
    :created_at => DateTime.t,
    :id => String.t,
    :is_active => boolean(),
    :max_tool_calls => integer(),
    :model => String.t,
    :name => String.t,
    :provider => String.t,
    :system_prompt => String.t,
    :tenant_id => String.t,
    :trigger_on => [String.t],
    :updated_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

