# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.AnlageSKfzHinweis do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :bezeichnung,
    :kennzeichen,
    :privat_anteil_prozent
  ]

  @type t :: %__MODULE__{
    :bezeichnung => String.t,
    :kennzeichen => String.t,
    :privat_anteil_prozent => String.t
  }

  def decode(value) do
    value
  end
end

