# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.AnlageGErgebnis do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :gewinn_verlust,
    :gewst_gezahlt,
    :gewst_messbetrag_approx,
    :gewst_pflichtig,
    :jahr,
    :kfz_hinweise
  ]

  @type t :: %__MODULE__{
    :gewinn_verlust => String.t,
    :gewst_gezahlt => String.t,
    :gewst_messbetrag_approx => String.t,
    :gewst_pflichtig => boolean(),
    :jahr => integer(),
    :kfz_hinweise => [SimpleBillyAPI.Model.AnlageGKfzHinweis.t]
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:kfz_hinweise, :list, SimpleBillyAPI.Model.AnlageGKfzHinweis)
  end
end

