# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ApiResponseUserProfileData do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :created_at,
    :email,
    :email_verified,
    :first_name,
    :full_name,
    :id,
    :last_name
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t,
    :email => String.t,
    :email_verified => boolean(),
    :first_name => String.t,
    :full_name => String.t,
    :id => String.t,
    :last_name => String.t
  }

  def decode(value) do
    value
  end
end

