# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ApiResponseVecUserTenantInfoDataInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :custom_domain,
    :role,
    :subdomain,
    :tenant_id,
    :tenant_name
  ]

  @type t :: %__MODULE__{
    :custom_domain => String.t | nil,
    :role => String.t,
    :subdomain => String.t | nil,
    :tenant_id => String.t,
    :tenant_name => String.t
  }

  def decode(value) do
    value
  end
end

