# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ApiResponseGdprExportData do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :activityLog,
    :apiKeys,
    :billing,
    :exportedAt,
    :generatedByAi,
    :notifications,
    :refreshTokens,
    :tenants,
    :usageEvents,
    :user
  ]

  @type t :: %__MODULE__{
    :activityLog => [SimpleBillyAPI.Model.GdprActivity.t],
    :apiKeys => [SimpleBillyAPI.Model.GdprApiKey.t],
    :billing => [SimpleBillyAPI.Model.GdprBillingInfo.t],
    :exportedAt => DateTime.t,
    :generatedByAi => boolean(),
    :notifications => [SimpleBillyAPI.Model.GdprNotification.t],
    :refreshTokens => [SimpleBillyAPI.Model.GdprRefreshToken.t],
    :tenants => [SimpleBillyAPI.Model.GdprTenant.t],
    :usageEvents => [SimpleBillyAPI.Model.GdprUsageEvent.t],
    :user => SimpleBillyAPI.Model.GdprUser.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:activityLog, :list, SimpleBillyAPI.Model.GdprActivity)
     |> Deserializer.deserialize(:apiKeys, :list, SimpleBillyAPI.Model.GdprApiKey)
     |> Deserializer.deserialize(:billing, :list, SimpleBillyAPI.Model.GdprBillingInfo)
     |> Deserializer.deserialize(:notifications, :list, SimpleBillyAPI.Model.GdprNotification)
     |> Deserializer.deserialize(:refreshTokens, :list, SimpleBillyAPI.Model.GdprRefreshToken)
     |> Deserializer.deserialize(:tenants, :list, SimpleBillyAPI.Model.GdprTenant)
     |> Deserializer.deserialize(:usageEvents, :list, SimpleBillyAPI.Model.GdprUsageEvent)
     |> Deserializer.deserialize(:user, :struct, SimpleBillyAPI.Model.GdprUser)
  end
end

