# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.Attachment do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :contactId,
    :fileName,
    :fileSize,
    :mimeType,
    :ocrText,
    :originalName,
    :pdfaPath,
    :sha256Hash,
    :uploadedBy
  ]

  @type t :: %__MODULE__{
    :contactId => String.t | nil,
    :fileName => String.t,
    :fileSize => integer() | nil,
    :mimeType => String.t | nil,
    :ocrText => String.t | nil,
    :originalName => String.t,
    :pdfaPath => String.t | nil,
    :sha256Hash => String.t | nil,
    :uploadedBy => String.t | nil
  }

  def decode(value) do
    value
  end
end

