# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.AuthResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :access_token,
    :message,
    :refresh_token,
    :success,
    :user
  ]

  @type t :: %__MODULE__{
    :access_token => String.t | nil,
    :message => String.t | nil,
    :refresh_token => String.t | nil,
    :success => boolean(),
    :user => SimpleBillyAPI.Model.Model.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:user, :struct, SimpleBillyAPI.Model.Model)
  end
end

