# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.Automation do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :automationKey,
    :config,
    :createdAt,
    :enabled,
    :lastRunAt,
    :nextRunAt,
    :tenantId,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :automationKey => String.t,
    :config => any() | nil,
    :createdAt => DateTime.t,
    :enabled => boolean(),
    :lastRunAt => DateTime.t | nil,
    :nextRunAt => DateTime.t | nil,
    :tenantId => String.t,
    :updatedAt => DateTime.t
  }

  def decode(value) do
    value
  end
end

