# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.BetriebsstaettenDetail do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :beschaefigte,
    :monatlicher_beitrag,
    :name
  ]

  @type t :: %__MODULE__{
    :beschaefigte => integer(),
    :monatlicher_beitrag => String.t,
    :name => String.t
  }

  def decode(value) do
    value
  end
end

