# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.BoxFit do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :height_cm,
    :item_count,
    :length_cm,
    :volume_cm3,
    :width_cm
  ]

  @type t :: %__MODULE__{
    :height_cm => float(),
    :item_count => integer(),
    :length_cm => float(),
    :volume_cm3 => float(),
    :width_cm => float()
  }

  def decode(value) do
    value
  end
end

