# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.BudgetGoalRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :monthly_goal,
    :year
  ]

  @type t :: %__MODULE__{
    :monthly_goal => String.t,
    :year => integer()
  }

  def decode(value) do
    value
  end
end

