# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.BudgetErgebnis do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :jahr,
    :monat,
    :monats_budget,
    :prognose_restjahr
  ]

  @type t :: %__MODULE__{
    :jahr => integer(),
    :monat => integer(),
    :monats_budget => [SimpleBillyAPI.Model.BudgetKategorie.t],
    :prognose_restjahr => [SimpleBillyAPI.Model.BudgetKategorie.t]
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:monats_budget, :list, SimpleBillyAPI.Model.BudgetKategorie)
     |> Deserializer.deserialize(:prognose_restjahr, :list, SimpleBillyAPI.Model.BudgetKategorie)
  end
end

