# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.BwaReport do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :expenses,
    :generated_at,
    :period,
    :revenue,
    :summary
  ]

  @type t :: %__MODULE__{
    :expenses => SimpleBillyAPI.Model.BwaExpenses.t,
    :generated_at => String.t,
    :period => String.t,
    :revenue => SimpleBillyAPI.Model.BwaRevenue.t,
    :summary => SimpleBillyAPI.Model.BwaSummary.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:expenses, :struct, SimpleBillyAPI.Model.BwaExpenses)
     |> Deserializer.deserialize(:revenue, :struct, SimpleBillyAPI.Model.BwaRevenue)
     |> Deserializer.deserialize(:summary, :struct, SimpleBillyAPI.Model.BwaSummary)
  end
end

