# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.BwaExpenses do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :expense_breakdown,
    :total_expenses
  ]

  @type t :: %__MODULE__{
    :expense_breakdown => [SimpleBillyAPI.Model.ExpenseItem.t],
    :total_expenses => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:expense_breakdown, :list, SimpleBillyAPI.Model.ExpenseItem)
  end
end

