# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.BwaRevenue do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :revenue_breakdown,
    :total_revenue
  ]

  @type t :: %__MODULE__{
    :revenue_breakdown => [SimpleBillyAPI.Model.RevenueItem.t],
    :total_revenue => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:revenue_breakdown, :list, SimpleBillyAPI.Model.RevenueItem)
  end
end

