# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.CartItemInput do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :product_id,
    :quantity
  ]

  @type t :: %__MODULE__{
    :product_id => String.t,
    :quantity => integer()
  }

  def decode(value) do
    value
  end
end

