# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.CategoryTotal do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :category_id,
    :share_pct,
    :tco2e
  ]

  @type t :: %__MODULE__{
    :category_id => String.t,
    :share_pct => float(),
    :tco2e => String.t
  }

  def decode(value) do
    value
  end
end

