# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ChangePasswordRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :current_password,
    :new_password
  ]

  @type t :: %__MODULE__{
    :current_password => String.t,
    :new_password => String.t
  }

  def decode(value) do
    value
  end
end

