# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ChangelogEntry do
  @moduledoc """
  One changelog entry for a plugin release.
  """

  @derive JSON.Encoder
  defstruct [
    :date,
    :notes,
    :version
  ]

  @type t :: %__MODULE__{
    :date => String.t,
    :notes => String.t,
    :version => String.t
  }

  def decode(value) do
    value
  end
end

