# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ComplianceEntry do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :description,
    :module,
    :regulations
  ]

  @type t :: %__MODULE__{
    :description => String.t,
    :module => String.t,
    :regulations => [String.t]
  }

  def decode(value) do
    value
  end
end

