# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ComplianceTrainingCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :assignable,
    :code,
    :description,
    :passScore,
    :pluginPlatform,
    :source,
    :title,
    :validityMonths
  ]

  @type t :: %__MODULE__{
    :assignable => boolean() | nil,
    :code => String.t | nil,
    :description => String.t | nil,
    :passScore => integer() | nil,
    :pluginPlatform => String.t | nil,
    :source => SimpleBillyAPI.Model.TrainingSource.t | nil,
    :title => String.t | nil,
    :validityMonths => integer() | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:source, :struct, SimpleBillyAPI.Model.TrainingSource)
  end
end

