# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ConfigFieldInfo do
  @moduledoc """
  Owned, API-safe copy of a [`ConfigField`] for DTOs / OpenAPI ([`ConfigField`] borrows `&'static str`, which cannot round-trip `Deserialize`).
  """

  @derive JSON.Encoder
  defstruct [
    :kind,
    :label,
    :name,
    :placeholder,
    :required
  ]

  @type t :: %__MODULE__{
    :kind => SimpleBillyAPI.Model.ConfigFieldKind.t,
    :label => String.t,
    :name => String.t,
    :placeholder => String.t | nil,
    :required => boolean()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:kind, :struct, SimpleBillyAPI.Model.ConfigFieldKind)
  end
end

