# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ConfigFieldKindOneOf3 do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :options,
    :type
  ]

  @type t :: %__MODULE__{
    :options => [String.t],
    :type => String.t
  }

  def decode(value) do
    value
  end
end

