# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ContactTimelineResponse do
  @moduledoc """
  Aggregated per-contact timeline.
  """

  @derive JSON.Encoder
  defstruct [
    :contactId,
    :events
  ]

  @type t :: %__MODULE__{
    :contactId => String.t,
    :events => [SimpleBillyAPI.Model.TimelineEvent.t]
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:events, :list, SimpleBillyAPI.Model.TimelineEvent)
  end
end

