# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ConvertResponse do
  @moduledoc """
  Response of the proforma → invoice conversion.
  """

  @derive JSON.Encoder
  defstruct [
    :invoiceId,
    :invoiceNumber,
    :proformaId,
    :proformaNumber
  ]

  @type t :: %__MODULE__{
    :invoiceId => String.t,
    :invoiceNumber => String.t,
    :proformaId => String.t,
    :proformaNumber => String.t
  }

  def decode(value) do
    value
  end
end

