# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.CostingLine do
  @moduledoc """
  A single costing line: material cost for one BOM component.
  """

  @derive JSON.Encoder
  defstruct [
    :lineCost,
    :name,
    :productId,
    :quantityPerUnit,
    :sku,
    :totalQuantity,
    :unitPurchasePrice
  ]

  @type t :: %__MODULE__{
    :lineCost => String.t,
    :name => String.t,
    :productId => String.t,
    :quantityPerUnit => integer(),
    :sku => String.t,
    :totalQuantity => integer(),
    :unitPurchasePrice => String.t | nil
  }

  def decode(value) do
    value
  end
end

