# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.CouponCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :description,
    :discountType,
    :discountValue,
    :expiresAt,
    :isActive,
    :isCombineable,
    :maxDiscountAmount,
    :maxUses,
    :maxUsesPerCustomer,
    :minOrderAmount,
    :productIds,
    :startsAt
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :description => String.t | nil,
    :discountType => SimpleBillyAPI.Model.DiscountType.t,
    :discountValue => String.t,
    :expiresAt => DateTime.t | nil,
    :isActive => boolean() | nil,
    :isCombineable => boolean() | nil,
    :maxDiscountAmount => String.t | nil,
    :maxUses => integer() | nil,
    :maxUsesPerCustomer => integer() | nil,
    :minOrderAmount => String.t | nil,
    :productIds => any() | nil,
    :startsAt => DateTime.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:discountType, :struct, SimpleBillyAPI.Model.DiscountType)
  end
end

