# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.CouponValidation do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :discount_type,
    :discount_value,
    :discounted_amount,
    :max_discount_amount,
    :reason,
    :valid
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :discount_type => String.t,
    :discount_value => String.t,
    :discounted_amount => String.t,
    :max_discount_amount => String.t | nil,
    :reason => String.t | nil,
    :valid => boolean()
  }

  def decode(value) do
    value
  end
end

