# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.CreateTicketRequest do
  @moduledoc """
  Request body for creating a support ticket. Wraps the generated `SupportTicketCreateDto` fields plus `message_body` which is not a Model field (used to create the initial `ticket_message`).
  """

  @derive JSON.Encoder
  defstruct [
    :channel_id,
    :channel_type,
    :customer_email,
    :customer_id,
    :customer_name,
    :external_id,
    :message_body,
    :order_ref,
    :subject
  ]

  @type t :: %__MODULE__{
    :channel_id => String.t | nil,
    :channel_type => String.t | nil,
    :customer_email => String.t | nil,
    :customer_id => String.t | nil,
    :customer_name => String.t | nil,
    :external_id => String.t | nil,
    :message_body => String.t,
    :order_ref => String.t | nil,
    :subject => String.t
  }

  def decode(value) do
    value
  end
end

