# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.CreateSubscriptionRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :event_type,
    :is_active,
    :name,
    :secret,
    :url
  ]

  @type t :: %__MODULE__{
    :event_type => String.t,
    :is_active => boolean() | nil,
    :name => String.t,
    :secret => String.t | nil,
    :url => String.t
  }

  def decode(value) do
    value
  end
end

