# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.CreateShipmentRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :carrier,
    :service,
    :weight_kg
  ]

  @type t :: %__MODULE__{
    :carrier => String.t,
    :service => String.t | nil,
    :weight_kg => float() | nil
  }

  def decode(value) do
    value
  end
end

