# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.CurrentInventoryValue do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :history,
    :product_count,
    :total_purchase_value,
    :total_sales_value
  ]

  @type t :: %__MODULE__{
    :history => [SimpleBillyAPI.Model.InventoryValuePoint.t],
    :product_count => integer(),
    :total_purchase_value => String.t,
    :total_sales_value => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:history, :list, SimpleBillyAPI.Model.InventoryValuePoint)
  end
end

