# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.CustomerUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :address,
    :contactPerson,
    :email,
    :externalOrderNumber,
    :name,
    :paymentGracePeriodDays,
    :phone,
    :vatId
  ]

  @type t :: %__MODULE__{
    :address => any() | nil,
    :contactPerson => String.t | nil,
    :email => String.t | nil,
    :externalOrderNumber => String.t | nil,
    :name => String.t | nil,
    :paymentGracePeriodDays => integer() | nil,
    :phone => String.t | nil,
    :vatId => String.t | nil
  }

  def decode(value) do
    value
  end
end

