# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.DataQuality do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :activity_lines,
    :activity_share_pct,
    :spend_lines
  ]

  @type t :: %__MODULE__{
    :activity_lines => integer(),
    :activity_share_pct => float(),
    :spend_lines => integer()
  }

  def decode(value) do
    value
  end
end

