# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.DatevBookingPreview do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :account_number,
    :debit_credit,
    :document_date,
    :document_text,
    :net_amount,
    :opposite_account,
    :tax_amount,
    :tax_rate
  ]

  @type t :: %__MODULE__{
    :account_number => String.t,
    :debit_credit => String.t,
    :document_date => String.t,
    :document_text => String.t,
    :net_amount => String.t,
    :opposite_account => String.t,
    :tax_amount => String.t | nil,
    :tax_rate => String.t | nil
  }

  def decode(value) do
    value
  end
end

