# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.DatevImportRow do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :account,
    :amount,
    :base_amount,
    :base_currency,
    :booking_text,
    :bu_key,
    :cost_center1,
    :cost_center2,
    :currency,
    :debit_credit,
    :discount,
    :document_date,
    :document_field2,
    :document_number,
    :eu_country_vat_id,
    :eu_tax_rate,
    :exchange_rate,
    :opposite_account
  ]

  @type t :: %__MODULE__{
    :account => String.t,
    :amount => String.t,
    :base_amount => String.t,
    :base_currency => String.t,
    :booking_text => String.t,
    :bu_key => String.t,
    :cost_center1 => String.t,
    :cost_center2 => String.t,
    :currency => String.t,
    :debit_credit => String.t,
    :discount => String.t,
    :document_date => String.t,
    :document_field2 => String.t,
    :document_number => String.t,
    :eu_country_vat_id => String.t,
    :eu_tax_rate => String.t,
    :exchange_rate => String.t,
    :opposite_account => String.t
  }

  def decode(value) do
    value
  end
end

