# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.DatevImportResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :count,
    :filename,
    :rows
  ]

  @type t :: %__MODULE__{
    :count => integer(),
    :filename => String.t,
    :rows => [SimpleBillyAPI.Model.DatevImportRow.t]
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:rows, :list, SimpleBillyAPI.Model.DatevImportRow)
  end
end

