# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.DeclarationUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :declarationType,
    :isCurrent,
    :text,
    :validFrom,
    :version
  ]

  @type t :: %__MODULE__{
    :declarationType => SimpleBillyAPI.Model.DeclarationType.t | nil,
    :isCurrent => boolean() | nil,
    :text => String.t | nil,
    :validFrom => Date.t | nil,
    :version => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:declarationType, :struct, SimpleBillyAPI.Model.DeclarationType)
  end
end

