# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.DeliverableResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :availableStock,
    :deliverableQuantity,
    :maxSellable,
    :productId,
    :reservedStock,
    :warehouseId
  ]

  @type t :: %__MODULE__{
    :availableStock => integer(),
    :deliverableQuantity => integer(),
    :maxSellable => integer() | nil,
    :productId => String.t,
    :reservedStock => integer(),
    :warehouseId => String.t | nil
  }

  def decode(value) do
    value
  end
end

