# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.DhlCredentials do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :api_key,
    :client_id,
    :client_secret
  ]

  @type t :: %__MODULE__{
    :api_key => String.t,
    :client_id => String.t | nil,
    :client_secret => String.t | nil
  }

  def decode(value) do
    value
  end
end

