# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.DpaAcceptRequest do
  @moduledoc """
  Request body to record DPA acceptance (`PUT /api/v1/gdpr/dpa`).
  """

  @derive JSON.Encoder
  defstruct [
    :acceptedByName,
    :version
  ]

  @type t :: %__MODULE__{
    :acceptedByName => String.t,
    :version => String.t
  }

  def decode(value) do
    value
  end
end

