# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ElsterStatus do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :cert_configured,
    :eric_available,
    :eric_version,
    :feature_enabled,
    :hint,
    :mode,
    :vendor_id_configured
  ]

  @type t :: %__MODULE__{
    :cert_configured => boolean(),
    :eric_available => boolean(),
    :eric_version => String.t | nil,
    :feature_enabled => boolean(),
    :hint => String.t,
    :mode => String.t,
    :vendor_id_configured => boolean()
  }

  def decode(value) do
    value
  end
end

