# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.EmailTemplateCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :body,
    :name,
    :status,
    :subject,
    :variables
  ]

  @type t :: %__MODULE__{
    :body => String.t,
    :name => String.t,
    :status => SimpleBillyAPI.Model.EmailTemplateStatus.t,
    :subject => String.t,
    :variables => any() | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.EmailTemplateStatus)
  end
end

