# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.EmissionEntry do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :activityValue,
    :categoryId,
    :description,
    :efSource,
    :efVersion,
    :method,
    :scope,
    :tco2e,
    :unit,
    :updatedAt,
    :year
  ]

  @type t :: %__MODULE__{
    :activityValue => String.t,
    :categoryId => String.t,
    :description => String.t,
    :efSource => String.t,
    :efVersion => String.t,
    :method => SimpleBillyAPI.Model.EmissionMethod.t,
    :scope => SimpleBillyAPI.Model.GhgScope.t,
    :tco2e => String.t,
    :unit => String.t,
    :updatedAt => DateTime.t | nil,
    :year => integer()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:method, :struct, SimpleBillyAPI.Model.EmissionMethod)
     |> Deserializer.deserialize(:scope, :struct, SimpleBillyAPI.Model.GhgScope)
  end
end

