# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.EmissionFactorResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :category_id,
    :kg_co2e_per_unit,
    :name_de,
    :source,
    :unit,
    :version
  ]

  @type t :: %__MODULE__{
    :category_id => String.t,
    :kg_co2e_per_unit => float(),
    :name_de => String.t,
    :source => String.t,
    :unit => String.t,
    :version => String.t
  }

  def decode(value) do
    value
  end
end

