# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.EmissionsReport do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :by_category,
    :by_scope,
    :by_year,
    :data_quality,
    :intensity_per_employee,
    :intensity_per_revenue_mio,
    :net_revenue,
    :spend_based_estimate_tco2e,
    :targets,
    :total_tco2e
  ]

  @type t :: %__MODULE__{
    :by_category => [SimpleBillyAPI.Model.CategoryTotal.t],
    :by_scope => [SimpleBillyAPI.Model.ScopeTotal.t],
    :by_year => [SimpleBillyAPI.Model.YearTotal.t],
    :data_quality => SimpleBillyAPI.Model.DataQuality.t,
    :intensity_per_employee => float() | nil,
    :intensity_per_revenue_mio => float() | nil,
    :net_revenue => float() | nil,
    :spend_based_estimate_tco2e => float() | nil,
    :targets => [SimpleBillyAPI.Model.TargetProgress.t],
    :total_tco2e => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:by_category, :list, SimpleBillyAPI.Model.CategoryTotal)
     |> Deserializer.deserialize(:by_scope, :list, SimpleBillyAPI.Model.ScopeTotal)
     |> Deserializer.deserialize(:by_year, :list, SimpleBillyAPI.Model.YearTotal)
     |> Deserializer.deserialize(:data_quality, :struct, SimpleBillyAPI.Model.DataQuality)
     |> Deserializer.deserialize(:targets, :list, SimpleBillyAPI.Model.TargetProgress)
  end
end

