# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.EmployeeCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :address,
    :backupEmployeeId,
    :bic,
    :city,
    :country,
    :dateOfBirth,
    :departmentId,
    :email,
    :firstName,
    :gender,
    :hireDate,
    :hourlyCost,
    :iban,
    :jobTitle,
    :lastLogin,
    :lastName,
    :lastUpdated,
    :monthlySalary,
    :phone,
    :state,
    :status,
    :userId,
    :weeklyHours,
    :zip
  ]

  @type t :: %__MODULE__{
    :address => String.t | nil,
    :backupEmployeeId => String.t | nil,
    :bic => String.t | nil,
    :city => String.t | nil,
    :country => SimpleBillyAPI.Model.CountryCode.t | nil,
    :dateOfBirth => Date.t | nil,
    :departmentId => String.t | nil,
    :email => String.t | nil,
    :firstName => String.t | nil,
    :gender => SimpleBillyAPI.Model.Gender.t | nil,
    :hireDate => Date.t | nil,
    :hourlyCost => String.t | nil,
    :iban => String.t | nil,
    :jobTitle => String.t | nil,
    :lastLogin => DateTime.t | nil,
    :lastName => String.t | nil,
    :lastUpdated => DateTime.t | nil,
    :monthlySalary => String.t | nil,
    :phone => String.t | nil,
    :state => String.t | nil,
    :status => SimpleBillyAPI.Model.EmployeeStatus.t | nil,
    :userId => String.t | nil,
    :weeklyHours => String.t | nil,
    :zip => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:country, :struct, SimpleBillyAPI.Model.CountryCode)
     |> Deserializer.deserialize(:gender, :struct, SimpleBillyAPI.Model.Gender)
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.EmployeeStatus)
  end
end

