# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.EuerDetailErgebnis do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :jahr,
    :zeilen
  ]

  @type t :: %__MODULE__{
    :jahr => integer(),
    :zeilen => [SimpleBillyAPI.Model.EuerZeileDetail.t]
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:zeilen, :list, SimpleBillyAPI.Model.EuerZeileDetail)
  end
end

