# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ExtraPayment do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :amount,
    :employee_id,
    :reason
  ]

  @type t :: %__MODULE__{
    :amount => String.t,
    :employee_id => String.t,
    :reason => String.t | nil
  }

  def decode(value) do
    value
  end
end

