# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.FeatureSettings do
  @moduledoc """
  Feature toggles for a tenant.
  """

  @derive JSON.Encoder
  defstruct [
    :onlineshop,
    :reportBilanz,
    :reportBwa,
    :reportEuer,
    :reportGewerbesteuer,
    :reportGuv,
    :reportKst,
    :reportUstva
  ]

  @type t :: %__MODULE__{
    :onlineshop => boolean(),
    :reportBilanz => boolean(),
    :reportBwa => boolean(),
    :reportEuer => boolean(),
    :reportGewerbesteuer => boolean(),
    :reportGuv => boolean(),
    :reportKst => boolean(),
    :reportUstva => boolean()
  }

  def decode(value) do
    value
  end
end

