# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.FristenErgebnis do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :anzahl,
    :fristen
  ]

  @type t :: %__MODULE__{
    :anzahl => integer(),
    :fristen => [SimpleBillyAPI.Model.FristEintrag.t]
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:fristen, :list, SimpleBillyAPI.Model.FristEintrag)
  end
end

