# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.GdprUsageEvent do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :createdAt,
    :eventType,
    :id,
    :quantity,
    :tenantId
  ]

  @type t :: %__MODULE__{
    :createdAt => DateTime.t,
    :eventType => String.t,
    :id => String.t,
    :quantity => integer(),
    :tenantId => String.t
  }

  def decode(value) do
    value
  end
end

