# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.GdprRefreshToken do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :createdAt,
    :expiresAt,
    :id,
    :revokedAt,
    :tenantId
  ]

  @type t :: %__MODULE__{
    :createdAt => DateTime.t,
    :expiresAt => DateTime.t,
    :id => String.t,
    :revokedAt => DateTime.t | nil,
    :tenantId => String.t
  }

  def decode(value) do
    value
  end
end

