# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.GewerbesteuerErgebnis do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :freibetrag,
    :gesamtbelastung,
    :gewerbeertrag,
    :hebesatz,
    :jahr,
    :koerperschaftsteuer,
    :land,
    :messbetrag,
    :steuer,
    :steuer_art
  ]

  @type t :: %__MODULE__{
    :freibetrag => String.t,
    :gesamtbelastung => String.t,
    :gewerbeertrag => String.t,
    :hebesatz => String.t,
    :jahr => integer(),
    :koerperschaftsteuer => String.t,
    :land => String.t,
    :messbetrag => String.t,
    :steuer => String.t,
    :steuer_art => String.t
  }

  def decode(value) do
    value
  end
end

