# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.GewinnverwendungsZeile do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :betrag,
    :label
  ]

  @type t :: %__MODULE__{
    :betrag => String.t,
    :label => String.t
  }

  def decode(value) do
    value
  end
end

