# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.GezReport do
  @moduledoc """
  Berechnungsergebnis des Rundfunkbeitrags für ein Unternehmen.
  """

  @derive JSON.Encoder
  defstruct [
    :beitragsfreie_kfz,
    :beitragspflichtige_kfz,
    :betriebsstaetten,
    :hinweis,
    :hotelzimmer_beitrag,
    :jaehrlicher_beitrag,
    :jahr,
    :kfz_beitrag,
    :monatlicher_beitrag,
    :vierteljaehrlicher_beitrag
  ]

  @type t :: %__MODULE__{
    :beitragsfreie_kfz => integer(),
    :beitragspflichtige_kfz => integer(),
    :betriebsstaetten => [SimpleBillyAPI.Model.BetriebsstaettenDetail.t],
    :hinweis => String.t,
    :hotelzimmer_beitrag => String.t,
    :jaehrlicher_beitrag => String.t,
    :jahr => integer(),
    :kfz_beitrag => String.t,
    :monatlicher_beitrag => String.t,
    :vierteljaehrlicher_beitrag => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:betriebsstaetten, :list, SimpleBillyAPI.Model.BetriebsstaettenDetail)
  end
end

