# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.GoodsReceipt do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :grNumber,
    :lineItems,
    :notes,
    :purchaseOrderId,
    :receiptDate,
    :supplierContactId,
    :supplierName,
    :warehouseId
  ]

  @type t :: %__MODULE__{
    :grNumber => String.t,
    :lineItems => any() | nil,
    :notes => String.t | nil,
    :purchaseOrderId => String.t | nil,
    :receiptDate => Date.t,
    :supplierContactId => String.t | nil,
    :supplierName => String.t | nil,
    :warehouseId => String.t
  }

  def decode(value) do
    value
  end
end

