# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.GroupFigure do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :bilanzsumme,
    :exemptionClaimed,
    :mitarbeiter,
    :nettoUmsatz,
    :parentName,
    :parentSitus,
    :year
  ]

  @type t :: %__MODULE__{
    :bilanzsumme => String.t | nil,
    :exemptionClaimed => boolean() | nil,
    :mitarbeiter => integer() | nil,
    :nettoUmsatz => String.t | nil,
    :parentName => String.t | nil,
    :parentSitus => String.t | nil,
    :year => integer()
  }

  def decode(value) do
    value
  end
end

