# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.GuVItem do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :account,
    :amount,
    :name
  ]

  @type t :: %__MODULE__{
    :account => String.t,
    :amount => String.t,
    :name => String.t
  }

  def decode(value) do
    value
  end
end

