# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.HebesatzLookup do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :bundesland,
    :country_code,
    :gemeinde_name,
    :gemeindeschluessel,
    :hebesatz_gewerbesteuer,
    :hebesatz_grundsteuer_b,
    :jahr,
    :landkreis,
    :valid_from,
    :valid_to
  ]

  @type t :: %__MODULE__{
    :bundesland => String.t,
    :country_code => String.t,
    :gemeinde_name => String.t,
    :gemeindeschluessel => String.t,
    :hebesatz_gewerbesteuer => float(),
    :hebesatz_grundsteuer_b => float() | nil,
    :jahr => integer(),
    :landkreis => String.t | nil,
    :valid_from => String.t,
    :valid_to => String.t | nil
  }

  def decode(value) do
    value
  end
end

