# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ImportTestRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :apiKey,
    :provider
  ]

  @type t :: %__MODULE__{
    :apiKey => String.t,
    :provider => String.t
  }

  def decode(value) do
    value
  end
end

