# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ImportStartRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :apiKey,
    :provider,
    :years
  ]

  @type t :: %__MODULE__{
    :apiKey => String.t,
    :provider => String.t,
    :years => [integer()]
  }

  def decode(value) do
    value
  end
end

