# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.IncomeStatement do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :expense_items,
    :net_income,
    :revenue_items,
    :total_expenses,
    :total_revenue
  ]

  @type t :: %__MODULE__{
    :expense_items => [SimpleBillyAPI.Model.PnLItem.t],
    :net_income => String.t,
    :revenue_items => [SimpleBillyAPI.Model.PnLItem.t],
    :total_expenses => String.t,
    :total_revenue => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:expense_items, :list, SimpleBillyAPI.Model.PnLItem)
     |> Deserializer.deserialize(:revenue_items, :list, SimpleBillyAPI.Model.PnLItem)
  end
end

