# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.InstituteDeadlines do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :abschlusspruefungMonths,
    :jahresabschlussBafinMonths,
    :offenlegungMonths
  ]

  @type t :: %__MODULE__{
    :abschlusspruefungMonths => integer() | nil,
    :jahresabschlussBafinMonths => integer() | nil,
    :offenlegungMonths => integer()
  }

  def decode(value) do
    value
  end
end

