# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.InstituteCheckItem do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :exists,
    :name,
    :source
  ]

  @type t :: %__MODULE__{
    :exists => boolean(),
    :name => String.t,
    :source => String.t
  }

  def decode(value) do
    value
  end
end

