# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.InventoryCountCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :countDate,
    :countNumber,
    :lineItems,
    :notes,
    :status,
    :warehouseId
  ]

  @type t :: %__MODULE__{
    :countDate => Date.t,
    :countNumber => String.t,
    :lineItems => any() | nil,
    :notes => String.t | nil,
    :status => SimpleBillyAPI.Model.InventoryCountStatus.t,
    :warehouseId => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.InventoryCountStatus)
  end
end

