# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.Invoice do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :attachments,
    :billingPeriodEnd,
    :billingPeriodStart,
    :cancellationDate,
    :cancellationInvoiceId,
    :cancellationReason,
    :contractId,
    :currency,
    :customerId,
    :discountAmount,
    :discountDays,
    :discountPercentage,
    :documentType,
    :dunningLevel,
    :inputVatAmount,
    :inputVatDeductible,
    :inputVatPercentage,
    :introductionText,
    :invoiceType,
    :isCancelled,
    :isDraft,
    :isEuAcquisition,
    :isEuDelivery,
    :isIntraCommunityAcquisition,
    :isReverseCharge,
    :issueDate,
    :ledgerAccount,
    :lineItems,
    :margin25a,
    :margin25aGross,
    :margin25aPurchasePrice,
    :notes,
    :orderNumber,
    :originalPdfPath,
    :paidAmount,
    :paymentDueDate,
    :paymentStatus,
    :paymentTermsText,
    :precedingSalesVoucherId,
    :precedingSalesVoucherType,
    :receiptConfirmationAvailable,
    :relatedInvoiceId,
    :relationshipType,
    :senderSnapshot,
    :sentAt,
    :servicePeriodEnd,
    :servicePeriodStart,
    :status,
    :subtotal,
    :supplierId,
    :taxExemptionReason,
    :totalAmount,
    :totalTax,
    :vatCountry,
    :vatSpecialCase
  ]

  @type t :: %__MODULE__{
    :attachments => any() | nil,
    :billingPeriodEnd => Date.t | nil,
    :billingPeriodStart => Date.t | nil,
    :cancellationDate => Date.t | nil,
    :cancellationInvoiceId => String.t | nil,
    :cancellationReason => String.t | nil,
    :contractId => String.t | nil,
    :currency => SimpleBillyAPI.Model.CurrencyCode.t,
    :customerId => String.t | nil,
    :discountAmount => String.t | nil,
    :discountDays => integer() | nil,
    :discountPercentage => String.t | nil,
    :documentType => SimpleBillyAPI.Model.DocumentType.t | nil,
    :dunningLevel => integer() | nil,
    :inputVatAmount => String.t | nil,
    :inputVatDeductible => boolean() | nil,
    :inputVatPercentage => String.t | nil,
    :introductionText => String.t | nil,
    :invoiceType => SimpleBillyAPI.Model.InvoiceType.t,
    :isCancelled => boolean() | nil,
    :isDraft => boolean() | nil,
    :isEuAcquisition => boolean() | nil,
    :isEuDelivery => boolean() | nil,
    :isIntraCommunityAcquisition => boolean() | nil,
    :isReverseCharge => boolean() | nil,
    :issueDate => Date.t,
    :ledgerAccount => String.t | nil,
    :lineItems => any() | nil,
    :margin25a => boolean() | nil,
    :margin25aGross => String.t | nil,
    :margin25aPurchasePrice => String.t | nil,
    :notes => String.t | nil,
    :orderNumber => String.t | nil,
    :originalPdfPath => String.t | nil,
    :paidAmount => String.t | nil,
    :paymentDueDate => Date.t | nil,
    :paymentStatus => SimpleBillyAPI.Model.PaymentStatus.t | nil,
    :paymentTermsText => String.t | nil,
    :precedingSalesVoucherId => String.t | nil,
    :precedingSalesVoucherType => SimpleBillyAPI.Model.PrecedingSalesVoucherType.t | nil,
    :receiptConfirmationAvailable => boolean() | nil,
    :relatedInvoiceId => String.t | nil,
    :relationshipType => String.t | nil,
    :senderSnapshot => any() | nil,
    :sentAt => DateTime.t | nil,
    :servicePeriodEnd => Date.t | nil,
    :servicePeriodStart => Date.t | nil,
    :status => SimpleBillyAPI.Model.InvoiceStatus.t,
    :subtotal => String.t,
    :supplierId => String.t | nil,
    :taxExemptionReason => String.t | nil,
    :totalAmount => String.t,
    :totalTax => String.t,
    :vatCountry => SimpleBillyAPI.Model.CountryCode.t | nil,
    :vatSpecialCase => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:currency, :struct, SimpleBillyAPI.Model.CurrencyCode)
     |> Deserializer.deserialize(:documentType, :struct, SimpleBillyAPI.Model.DocumentType)
     |> Deserializer.deserialize(:invoiceType, :struct, SimpleBillyAPI.Model.InvoiceType)
     |> Deserializer.deserialize(:paymentStatus, :struct, SimpleBillyAPI.Model.PaymentStatus)
     |> Deserializer.deserialize(:precedingSalesVoucherType, :struct, SimpleBillyAPI.Model.PrecedingSalesVoucherType)
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.InvoiceStatus)
     |> Deserializer.deserialize(:vatCountry, :struct, SimpleBillyAPI.Model.CountryCode)
  end
end

