# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.InvoiceLineItem do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :article_number,
    :description,
    :discount_amount,
    :discount_percentage,
    :input_vat_deductible,
    :input_vat_rate,
    :is_intra_community_acquisition,
    :is_margin_25a,
    :ledger_account,
    :line_total,
    :line_total_gross,
    :margin_25a_purchase_price,
    :meter_point_id,
    :position,
    :price_components,
    :product_id,
    :product_sku,
    :quantity,
    :supplier_article_number,
    :tax_rate,
    :unit,
    :unit_price,
    :usage_data_id,
    :vat_rate_nominal,
    :vat_special_case
  ]

  @type t :: %__MODULE__{
    :article_number => String.t | nil,
    :description => String.t,
    :discount_amount => String.t | nil,
    :discount_percentage => String.t | nil,
    :input_vat_deductible => boolean() | nil,
    :input_vat_rate => String.t | nil,
    :is_intra_community_acquisition => boolean() | nil,
    :is_margin_25a => boolean() | nil,
    :ledger_account => String.t | nil,
    :line_total => String.t,
    :line_total_gross => String.t | nil,
    :margin_25a_purchase_price => String.t | nil,
    :meter_point_id => String.t | nil,
    :position => integer(),
    :price_components => any() | nil,
    :product_id => String.t | nil,
    :product_sku => String.t | nil,
    :quantity => String.t,
    :supplier_article_number => String.t | nil,
    :tax_rate => String.t | nil,
    :unit => any() | nil,
    :unit_price => String.t,
    :usage_data_id => String.t | nil,
    :vat_rate_nominal => String.t | nil,
    :vat_special_case => String.t | nil
  }

  def decode(value) do
    value
  end
end

