# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.InvoiceMatchRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :supplier_invoice_id
  ]

  @type t :: %__MODULE__{
    :supplier_invoice_id => String.t
  }

  def decode(value) do
    value
  end
end

