# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.JobPostingFilter do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :page,
    :pageSize,
    :status
  ]

  @type t :: %__MODULE__{
    :page => integer() | nil,
    :pageSize => integer() | nil,
    :status => String.t | nil
  }

  def decode(value) do
    value
  end
end

