# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.JobPostingUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :currency,
    :department,
    :description,
    :employmentType,
    :location,
    :remote,
    :requiredSkills,
    :requirements,
    :salaryMax,
    :salaryMin,
    :status,
    :title
  ]

  @type t :: %__MODULE__{
    :currency => String.t | nil,
    :department => String.t | nil,
    :description => String.t | nil,
    :employmentType => SimpleBillyAPI.Model.EmploymentType.t | nil,
    :location => String.t | nil,
    :remote => boolean() | nil,
    :requiredSkills => any() | nil,
    :requirements => String.t | nil,
    :salaryMax => integer() | nil,
    :salaryMin => integer() | nil,
    :status => SimpleBillyAPI.Model.JobPostingStatus.t | nil,
    :title => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:employmentType, :struct, SimpleBillyAPI.Model.EmploymentType)
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.JobPostingStatus)
  end
end

