# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.JobApplication do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :cvFile,
    :cvText,
    :email,
    :matchReason,
    :matchScore,
    :name,
    :phone,
    :postingId,
    :source,
    :status
  ]

  @type t :: %__MODULE__{
    :cvFile => String.t | nil,
    :cvText => String.t | nil,
    :email => String.t | nil,
    :matchReason => String.t | nil,
    :matchScore => integer() | nil,
    :name => String.t | nil,
    :phone => String.t | nil,
    :postingId => String.t | nil,
    :source => String.t,
    :status => SimpleBillyAPI.Model.ApplicationStatus.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.ApplicationStatus)
  end
end

