# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.JobTitleGap do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :employee_count,
    :female_mean_hourly,
    :job_title,
    :male_mean_hourly,
    :mean_gap_pct,
    :median_gap_pct
  ]

  @type t :: %__MODULE__{
    :employee_count => integer(),
    :female_mean_hourly => String.t,
    :job_title => String.t,
    :male_mean_hourly => String.t,
    :mean_gap_pct => float(),
    :median_gap_pct => float()
  }

  def decode(value) do
    value
  end
end

