# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.KontoItem do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :anfangsbestand,
    :haben_umsatz,
    :konto,
    :name,
    :saldo,
    :soll_umsatz
  ]

  @type t :: %__MODULE__{
    :anfangsbestand => String.t,
    :haben_umsatz => String.t,
    :konto => String.t,
    :name => String.t,
    :saldo => String.t,
    :soll_umsatz => String.t
  }

  def decode(value) do
    value
  end
end

