# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.KstErgebnis do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :gesamt,
    :gesamtbelastung,
    :gewerbesteuer,
    :gewinn,
    :ist_kapitalgesellschaft,
    :jahr,
    :koerperschaftsteuer,
    :solidaritaetszuschlag
  ]

  @type t :: %__MODULE__{
    :gesamt => String.t,
    :gesamtbelastung => String.t,
    :gewerbesteuer => String.t,
    :gewinn => String.t,
    :ist_kapitalgesellschaft => boolean(),
    :jahr => integer(),
    :koerperschaftsteuer => String.t,
    :solidaritaetszuschlag => String.t
  }

  def decode(value) do
    value
  end
end

