# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.LaborCostRow do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :cost,
    :employeeId,
    :groupKey,
    :hours,
    :name
  ]

  @type t :: %__MODULE__{
    :cost => String.t,
    :employeeId => String.t | nil,
    :groupKey => String.t,
    :hours => String.t,
    :name => String.t | nil
  }

  def decode(value) do
    value
  end
end

