# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.LegalDocument do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :content,
    :docType,
    :lang,
    :title
  ]

  @type t :: %__MODULE__{
    :content => String.t,
    :docType => SimpleBillyAPI.Model.LegalDocType.t,
    :lang => SimpleBillyAPI.Model.LanguageCode.t,
    :title => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:docType, :struct, SimpleBillyAPI.Model.LegalDocType)
     |> Deserializer.deserialize(:lang, :struct, SimpleBillyAPI.Model.LanguageCode)
  end
end

