# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.LegalDocumentReset do
  @moduledoc """
  Optional filter for `POST /api/v1/legal/documents/reset`; empty body restores every document of the tenant.
  """

  @derive JSON.Encoder
  defstruct [
    :docType,
    :lang
  ]

  @type t :: %__MODULE__{
    :docType => String.t | nil,
    :lang => String.t | nil
  }

  def decode(value) do
    value
  end
end

