# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.LegalDocType do
  @moduledoc """
  Legal document type (matches `DOC_TYPES` in legal_defaults.rs).
  """

  @derive JSON.Encoder
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }

  def decode(value) do
    value
  end
end

