# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.LoginRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :password,
    :totp_code
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :password => String.t,
    :totp_code => String.t | nil
  }

  def decode(value) do
    value
  end
end

