# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.MarketplaceSyncLog do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :completedAt,
    :connectionId,
    :errorMessage,
    :itemsFailed,
    :itemsSynced,
    :platform,
    :startedAt,
    :status,
    :syncType
  ]

  @type t :: %__MODULE__{
    :completedAt => DateTime.t | nil,
    :connectionId => String.t,
    :errorMessage => String.t | nil,
    :itemsFailed => integer(),
    :itemsSynced => integer(),
    :platform => String.t,
    :startedAt => DateTime.t,
    :status => SimpleBillyAPI.Model.SyncLogStatus.t,
    :syncType => SimpleBillyAPI.Model.SyncType.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.SyncLogStatus)
     |> Deserializer.deserialize(:syncType, :struct, SimpleBillyAPI.Model.SyncType)
  end
end

