# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.MarketplaceConnection do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :config,
    :connection_id,
    :connector_type,
    :created_at,
    :is_active,
    :label,
    :last_sync_at,
    :platform,
    :platform_user_id,
    :scopes,
    :shop_domain,
    :shop_name,
    :sync_status,
    :tenant_id,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :config => any() | nil,
    :connection_id => String.t,
    :connector_type => SimpleBillyAPI.Model.ConnectorType.t,
    :created_at => DateTime.t,
    :is_active => boolean(),
    :label => String.t,
    :last_sync_at => DateTime.t | nil,
    :platform => String.t,
    :platform_user_id => String.t | nil,
    :scopes => String.t | nil,
    :shop_domain => String.t | nil,
    :shop_name => String.t | nil,
    :sync_status => String.t | nil,
    :tenant_id => String.t,
    :updated_at => DateTime.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:connector_type, :struct, SimpleBillyAPI.Model.ConnectorType)
  end
end

