# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.MeteredUsage do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :limit,
    :meter,
    :used
  ]

  @type t :: %__MODULE__{
    :limit => integer(),
    :meter => String.t,
    :used => integer()
  }

  def decode(value) do
    value
  end
end

