# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.NotificationDto do
  @moduledoc """
  Wire shape of a notification row (mirrors frontend Notification type).
  """

  @derive JSON.Encoder
  defstruct [
    :created_at,
    :id,
    :is_read,
    :message,
    :sent_via_email,
    :tenant_id,
    :title,
    :user_id
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t,
    :id => String.t,
    :is_read => boolean(),
    :message => String.t | nil,
    :sent_via_email => boolean(),
    :tenant_id => String.t,
    :title => String.t,
    :user_id => String.t
  }

  def decode(value) do
    value
  end
end

