# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.OAuthCallbackRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :config,
    :connection_id,
    :platform,
    :shop_domain,
    :state
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :config => any() | nil,
    :connection_id => String.t | nil,
    :platform => String.t,
    :shop_domain => String.t | nil,
    :state => String.t
  }

  def decode(value) do
    value
  end
end

