# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.OAuthAuthorizeRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :config,
    :platform,
    :redirect_uri
  ]

  @type t :: %__MODULE__{
    :config => any() | nil,
    :platform => String.t,
    :redirect_uri => String.t
  }

  def decode(value) do
    value
  end
end

