# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.OrderStateUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :send_state_to_shop,
    :state
  ]

  @type t :: %__MODULE__{
    :send_state_to_shop => boolean() | nil,
    :state => String.t
  }

  def decode(value) do
    value
  end
end

