# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.OrderUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :auditLog,
    :currency,
    :customerId,
    :externalReference,
    :invoiceAddress,
    :items,
    :language,
    :orderStatus,
    :paymentMethod,
    :shippingAddress,
    :shippingCost,
    :shippingMethod,
    :shippingWeight,
    :tags,
    :totalCost
  ]

  @type t :: %__MODULE__{
    :auditLog => any() | nil,
    :currency => String.t | nil,
    :customerId => String.t | nil,
    :externalReference => String.t | nil,
    :invoiceAddress => any() | nil,
    :items => any() | nil,
    :language => SimpleBillyAPI.Model.LanguageCode.t | nil,
    :orderStatus => SimpleBillyAPI.Model.OrderStatus.t | nil,
    :paymentMethod => SimpleBillyAPI.Model.PaymentMethod.t | nil,
    :shippingAddress => any() | nil,
    :shippingCost => String.t | nil,
    :shippingMethod => String.t | nil,
    :shippingWeight => String.t | nil,
    :tags => [String.t] | nil,
    :totalCost => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:language, :struct, SimpleBillyAPI.Model.LanguageCode)
     |> Deserializer.deserialize(:orderStatus, :struct, SimpleBillyAPI.Model.OrderStatus)
     |> Deserializer.deserialize(:paymentMethod, :struct, SimpleBillyAPI.Model.PaymentMethod)
  end
end

