# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.OssDependency do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :dependency_type,
    :license,
    :name,
    :version
  ]

  @type t :: %__MODULE__{
    :dependency_type => String.t,
    :license => String.t | nil,
    :name => String.t,
    :version => String.t
  }

  def decode(value) do
    value
  end
end

