# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.OssReport do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :dependencies,
    :total_count
  ]

  @type t :: %__MODULE__{
    :dependencies => [SimpleBillyAPI.Model.OssDependency.t],
    :total_count => integer()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:dependencies, :list, SimpleBillyAPI.Model.OssDependency)
  end
end

