# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PackingVideoResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :message,
    :recording_url,
    :success
  ]

  @type t :: %__MODULE__{
    :message => String.t,
    :recording_url => String.t | nil,
    :success => boolean()
  }

  def decode(value) do
    value
  end
end

