# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PackingQueue do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :items,
    :page,
    :page_size,
    :total_count
  ]

  @type t :: %__MODULE__{
    :items => [SimpleBillyAPI.Model.PackingQueueItem.t],
    :page => integer(),
    :page_size => integer(),
    :total_count => integer()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, SimpleBillyAPI.Model.PackingQueueItem)
  end
end

