# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PackingCompleteResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :message,
    :new_state,
    :order_number,
    :success
  ]

  @type t :: %__MODULE__{
    :message => String.t,
    :new_state => String.t,
    :order_number => String.t,
    :success => boolean()
  }

  def decode(value) do
    value
  end
end

