# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PackingCompleteRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :notes,
    :order_number,
    :shipment_id,
    :video_url
  ]

  @type t :: %__MODULE__{
    :notes => String.t | nil,
    :order_number => String.t,
    :shipment_id => String.t | nil,
    :video_url => String.t | nil
  }

  def decode(value) do
    value
  end
end

