# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PartialFeatureSettings do
  @moduledoc """
  Partial feature toggles: `None` keeps the company-type default, `Some` overrides it.
  """

  @derive JSON.Encoder
  defstruct [
    :onlineshop,
    :reportBilanz,
    :reportBwa,
    :reportEuer,
    :reportGewerbesteuer,
    :reportGuv,
    :reportKst,
    :reportUstva
  ]

  @type t :: %__MODULE__{
    :onlineshop => boolean() | nil,
    :reportBilanz => boolean() | nil,
    :reportBwa => boolean() | nil,
    :reportEuer => boolean() | nil,
    :reportGewerbesteuer => boolean() | nil,
    :reportGuv => boolean() | nil,
    :reportKst => boolean() | nil,
    :reportUstva => boolean() | nil
  }

  def decode(value) do
    value
  end
end

