# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ParticipationCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :acquiredAt,
    :boardAppointment,
    :companyName,
    :controlAgreement,
    :legalForm,
    :ownershipPct,
    :purposeVehicle,
    :votingMajority
  ]

  @type t :: %__MODULE__{
    :acquiredAt => Date.t | nil,
    :boardAppointment => boolean() | nil,
    :companyName => String.t | nil,
    :controlAgreement => boolean() | nil,
    :legalForm => String.t | nil,
    :ownershipPct => String.t | nil,
    :purposeVehicle => boolean() | nil,
    :votingMajority => boolean() | nil
  }

  def decode(value) do
    value
  end
end

