# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PayGapExportResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :csv_content,
    :filename
  ]

  @type t :: %__MODULE__{
    :csv_content => String.t,
    :filename => String.t
  }

  def decode(value) do
    value
  end
end

