# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PaymentCondition do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :discount_days,
    :discount_percentage,
    :id,
    :name,
    :payment_term_days
  ]

  @type t :: %__MODULE__{
    :discount_days => integer(),
    :discount_percentage => float(),
    :id => String.t,
    :name => String.t,
    :payment_term_days => integer()
  }

  def decode(value) do
    value
  end
end

