# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.Payment do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :amount,
    :attachment,
    :currency,
    :customerId,
    :description,
    :metadata,
    :method,
    :paymentDate,
    :reference
  ]

  @type t :: %__MODULE__{
    :amount => String.t | nil,
    :attachment => any() | nil,
    :currency => String.t | nil,
    :customerId => String.t | nil,
    :description => String.t | nil,
    :metadata => any() | nil,
    :method => SimpleBillyAPI.Model.PaymentMethod.t | nil,
    :paymentDate => DateTime.t | nil,
    :reference => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:method, :struct, SimpleBillyAPI.Model.PaymentMethod)
  end
end

