# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PaymentGatewayCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :config,
    :createdAt,
    :deletedAt,
    :enabled,
    :gatewayType,
    :label,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :config => any() | nil,
    :createdAt => DateTime.t,
    :deletedAt => DateTime.t | nil,
    :enabled => boolean(),
    :gatewayType => SimpleBillyAPI.Model.GatewayType.t,
    :label => String.t,
    :updatedAt => DateTime.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:gatewayType, :struct, SimpleBillyAPI.Model.GatewayType)
  end
end

