# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PayrollSummary do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :firstName,
    :hourlyGross,
    :id,
    :jobTitle,
    :lastName,
    :monthlySalary,
    :months,
    :weeklyHours,
    :year
  ]

  @type t :: %__MODULE__{
    :firstName => String.t,
    :hourlyGross => String.t | nil,
    :id => String.t,
    :jobTitle => String.t,
    :lastName => String.t,
    :monthlySalary => String.t | nil,
    :months => [SimpleBillyAPI.Model.PayrollMonth.t],
    :weeklyHours => String.t | nil,
    :year => integer()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:months, :list, SimpleBillyAPI.Model.PayrollMonth)
  end
end

