# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PayrollRunApi do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :approved_at,
    :approved_by,
    :created_at,
    :entries,
    :month,
    :payment_date,
    :period_label,
    :run_id,
    :status,
    :tenant_id,
    :total_employee_count,
    :total_employer_cost,
    :total_gross,
    :total_net,
    :total_social_security,
    :total_taxes,
    :updated_at,
    :year
  ]

  @type t :: %__MODULE__{
    :approved_at => DateTime.t | nil,
    :approved_by => String.t | nil,
    :created_at => DateTime.t,
    :entries => [SimpleBillyAPI.Model.PayrollEntryApi.t],
    :month => integer(),
    :payment_date => Date.t | nil,
    :period_label => String.t,
    :run_id => String.t,
    :status => SimpleBillyAPI.Model.PayrollRunStatus.t,
    :tenant_id => String.t,
    :total_employee_count => integer(),
    :total_employer_cost => String.t,
    :total_gross => String.t,
    :total_net => String.t,
    :total_social_security => String.t,
    :total_taxes => String.t,
    :updated_at => DateTime.t | nil,
    :year => integer()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:entries, :list, SimpleBillyAPI.Model.PayrollEntryApi)
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.PayrollRunStatus)
  end
end

