# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PayrollEntryApi do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :av_employee,
    :av_employer,
    :church_tax_amount,
    :employee,
    :employee_id,
    :entry_id,
    :extra_payment_reason,
    :extra_payments,
    :gross_salary,
    :kv_employee,
    :kv_employer,
    :lohnsteuer,
    :net_salary,
    :notes,
    :pv_employee,
    :pv_employer,
    :run_id,
    :rv_employee,
    :rv_employer,
    :sick_days,
    :soli,
    :status,
    :total_deductions,
    :total_employer_cost,
    :vacation_days_used
  ]

  @type t :: %__MODULE__{
    :av_employee => String.t,
    :av_employer => String.t,
    :church_tax_amount => String.t,
    :employee => SimpleBillyAPI.Model.Employee.t | nil,
    :employee_id => String.t,
    :entry_id => String.t,
    :extra_payment_reason => String.t | nil,
    :extra_payments => String.t,
    :gross_salary => String.t,
    :kv_employee => String.t,
    :kv_employer => String.t,
    :lohnsteuer => String.t,
    :net_salary => String.t,
    :notes => String.t | nil,
    :pv_employee => String.t,
    :pv_employer => String.t,
    :run_id => String.t,
    :rv_employee => String.t,
    :rv_employer => String.t,
    :sick_days => integer(),
    :soli => String.t,
    :status => SimpleBillyAPI.Model.PayrollRunStatus.t,
    :total_deductions => String.t,
    :total_employer_cost => String.t,
    :vacation_days_used => integer()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:employee, :struct, SimpleBillyAPI.Model.Employee)
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.PayrollRunStatus)
  end
end

