# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PayrollCreatePayload do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :employee_ids,
    :extra_payments,
    :month,
    :year
  ]

  @type t :: %__MODULE__{
    :employee_ids => [String.t],
    :extra_payments => [SimpleBillyAPI.Model.ExtraPayment.t] | nil,
    :month => integer(),
    :year => integer()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:extra_payments, :list, SimpleBillyAPI.Model.ExtraPayment)
  end
end

