# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PayrollPayPayload do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :payment_date
  ]

  @type t :: %__MODULE__{
    :payment_date => Date.t
  }

  def decode(value) do
    value
  end
end

