# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PlanFeatures do
  @moduledoc """
  Feature flags per plan.
  """

  @derive JSON.Encoder
  defstruct [
    :connectors,
    :erp,
    :fancyReports,
    :taxAutomations
  ]

  @type t :: %__MODULE__{
    :connectors => boolean(),
    :erp => boolean(),
    :fancyReports => boolean(),
    :taxAutomations => boolean()
  }

  def decode(value) do
    value
  end
end

