# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PlanLimits do
  @moduledoc """
  Per-plan numeric limits. `-1` in any field means unlimited.
  """

  @derive JSON.Encoder
  defstruct [
    :maxConnectors,
    :maxInvoicesPerMonth,
    :maxUsers,
    :metered,
    :paidConnectors
  ]

  @type t :: %__MODULE__{
    :maxConnectors => integer(),
    :maxInvoicesPerMonth => integer(),
    :maxUsers => integer(),
    :metered => %{optional(String.t) => integer()} | nil,
    :paidConnectors => [String.t]
  }

  def decode(value) do
    value
  end
end

