# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.Plan do
  @moduledoc """
  One canonical plan. `price_eur == -1.0` means custom pricing.
  """

  @derive JSON.Encoder
  defstruct [
    :features,
    :id,
    :limits,
    :name,
    :priceEur
  ]

  @type t :: %__MODULE__{
    :features => SimpleBillyAPI.Model.PlanFeatures.t,
    :id => String.t,
    :limits => SimpleBillyAPI.Model.PlanLimits.t,
    :name => String.t,
    :priceEur => float()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:features, :struct, SimpleBillyAPI.Model.PlanFeatures)
     |> Deserializer.deserialize(:limits, :struct, SimpleBillyAPI.Model.PlanLimits)
  end
end

