# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PlatformInfo do
  @moduledoc """
  Public metadata for one registered plugin (admin UI). Maps 1:1 from [`plugin_core::PluginInfo`] (same field shape as before).
  """

  @derive JSON.Encoder
  defstruct [
    :author,
    :changelog,
    :config_field_names,
    :config_fields,
    :display_name,
    :platform,
    :pricing,
    :supported_entities,
    :supports_export,
    :supports_import,
    :supports_oauth,
    :version
  ]

  @type t :: %__MODULE__{
    :author => String.t,
    :changelog => [SimpleBillyAPI.Model.ChangelogEntry.t],
    :config_field_names => [String.t],
    :config_fields => [SimpleBillyAPI.Model.ConfigFieldInfo.t],
    :display_name => String.t,
    :platform => String.t,
    :pricing => SimpleBillyAPI.Model.PluginPricing.t,
    :supported_entities => [String.t],
    :supports_export => boolean(),
    :supports_import => boolean(),
    :supports_oauth => boolean(),
    :version => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:changelog, :list, SimpleBillyAPI.Model.ChangelogEntry)
     |> Deserializer.deserialize(:config_fields, :list, SimpleBillyAPI.Model.ConfigFieldInfo)
     |> Deserializer.deserialize(:pricing, :struct, SimpleBillyAPI.Model.PluginPricing)
  end
end

