# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PlausibilityReport do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :checks,
    :generated_at,
    :summary
  ]

  @type t :: %__MODULE__{
    :checks => [SimpleBillyAPI.Model.PlausibilityCheck.t],
    :generated_at => String.t,
    :summary => SimpleBillyAPI.Model.PlausibilitySummary.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:checks, :list, SimpleBillyAPI.Model.PlausibilityCheck)
     |> Deserializer.deserialize(:summary, :struct, SimpleBillyAPI.Model.PlausibilitySummary)
  end
end

