# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PlausibilityCheck do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :detail,
    :id,
    :name,
    :severity,
    :status
  ]

  @type t :: %__MODULE__{
    :detail => String.t,
    :id => String.t,
    :name => String.t,
    :severity => SimpleBillyAPI.Model.Severity.t,
    :status => SimpleBillyAPI.Model.CheckStatus.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:severity, :struct, SimpleBillyAPI.Model.Severity)
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.CheckStatus)
  end
end

