# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PluginErrorOneOf5 do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :ValidationError
  ]

  @type t :: %__MODULE__{
    :ValidationError => [map()]
  }

  def decode(value) do
    value
  end
end

