# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PluginPricing do
  @moduledoc """
  How a plugin is priced in the marketplace. Tagged on `type` so the same enum deserializes both the API DTO and the `plugin_marketplace.json` manifest (`{\"type\":\"free\"}` / `{\"type\":\"one_time\",\"price\":99.0}` / `{\"type\":\"recurring\",\"price_per_month\":19.9}`).
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :price,
    :price_per_month
  ]

  @type t :: %__MODULE__{
    :type => any(),
    :price => any(),
    :price_per_month => any()
  }

  def decode(value) do
    value
  end
end

