# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PluginError do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :BadRequest,
    :NotFound,
    :Unauthorized,
    :InternalError,
    :DatabaseError,
    :ValidationError,
    :NotImplemented
  ]

  @type t :: %__MODULE__{
    :BadRequest => [any()],
    :NotFound => [any()],
    :Unauthorized => [any()],
    :InternalError => [any()],
    :DatabaseError => [any()],
    :ValidationError => [any()],
    :NotImplemented => any()
  }

  def decode(value) do
    value
  end
end

