# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PluginPricingOneOf2 do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :price_per_month,
    :type
  ]

  @type t :: %__MODULE__{
    :price_per_month => float(),
    :type => String.t
  }

  def decode(value) do
    value
  end
end

