# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PosTable do
  @moduledoc """
  A physical table at a restaurant/cafe POS. `current_order_number` links the open order occupying the table; `None` means free.
  """

  @derive JSON.Encoder
  defstruct [
    :currentOrderNumber,
    :name,
    :status
  ]

  @type t :: %__MODULE__{
    :currentOrderNumber => String.t | nil,
    :name => String.t,
    :status => SimpleBillyAPI.Model.PosTableStatus.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.PosTableStatus)
  end
end

