# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PosRegisterCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :status
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :status => SimpleBillyAPI.Model.PosRegisterStatus.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.PosRegisterStatus)
  end
end

