# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PostingCategory do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :account_number,
    :account_number_skr03,
    :account_number_skr04,
    :account_number_skr49,
    :category_id,
    :default_vat_rate,
    :description,
    :eks_category,
    :is_active,
    :is_system,
    :name,
    :skr_version,
    :type
  ]

  @type t :: %__MODULE__{
    :account_number => String.t | nil,
    :account_number_skr03 => String.t | nil,
    :account_number_skr04 => String.t | nil,
    :account_number_skr49 => String.t | nil,
    :category_id => String.t,
    :default_vat_rate => integer(),
    :description => String.t | nil,
    :eks_category => String.t | nil,
    :is_active => boolean(),
    :is_system => boolean(),
    :name => String.t,
    :skr_version => String.t,
    :type => String.t
  }

  def decode(value) do
    value
  end
end

