# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PriceTier do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :customerGroupId,
    :minQuantity,
    :productId,
    :unitPrice
  ]

  @type t :: %__MODULE__{
    :customerGroupId => String.t | nil,
    :minQuantity => integer() | nil,
    :productId => String.t,
    :unitPrice => String.t
  }

  def decode(value) do
    value
  end
end

