# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ProductCategoryCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :description,
    :name,
    :parentCategoryId,
    :sortOrder
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :name => String.t,
    :parentCategoryId => String.t | nil,
    :sortOrder => integer()
  }

  def decode(value) do
    value
  end
end

