# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ProductVariantUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :barcode,
    :imageLink,
    :isActive,
    :name,
    :optionValues,
    :price,
    :priceDelta,
    :productId,
    :sku,
    :stockQuantity
  ]

  @type t :: %__MODULE__{
    :barcode => String.t | nil,
    :imageLink => String.t | nil,
    :isActive => boolean() | nil,
    :name => String.t | nil,
    :optionValues => any() | nil,
    :price => String.t | nil,
    :priceDelta => String.t | nil,
    :productId => String.t | nil,
    :sku => String.t | nil,
    :stockQuantity => integer() | nil
  }

  def decode(value) do
    value
  end
end

