# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ProductAttributeCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :isFilterable,
    :name,
    :position,
    :productId,
    :unit,
    :value
  ]

  @type t :: %__MODULE__{
    :isFilterable => boolean() | nil,
    :name => String.t,
    :position => integer() | nil,
    :productId => String.t,
    :unit => String.t | nil,
    :value => String.t
  }

  def decode(value) do
    value
  end
end

