# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ProductUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :availability,
    :barcode,
    :brand,
    :categoryId,
    :condition,
    :defaultLedgerAccount,
    :defaultPrice,
    :defaultPriceFormulaId,
    :defaultTaxRate,
    :description,
    :gtin,
    :height,
    :imageLink,
    :images,
    :isTaxable,
    :length,
    :link,
    :maxStock,
    :minStock,
    :mpn,
    :name,
    :packageHeight,
    :packageLength,
    :packageWeightUnit,
    :packageWeightValue,
    :packageWidth,
    :productCode,
    :productType,
    :purchasePrice,
    :reorderQuantity,
    :salePrice,
    :shippingPrice,
    :shippingRequiresInsurance,
    :sku,
    :stockQuantity,
    :tags,
    :taxPrice,
    :trackBatch,
    :trackSerial,
    :unit,
    :weightUnit,
    :weightValue,
    :width
  ]

  @type t :: %__MODULE__{
    :availability => String.t | nil,
    :barcode => String.t | nil,
    :brand => String.t | nil,
    :categoryId => String.t | nil,
    :condition => String.t | nil,
    :defaultLedgerAccount => String.t | nil,
    :defaultPrice => String.t | nil,
    :defaultPriceFormulaId => String.t | nil,
    :defaultTaxRate => String.t | nil,
    :description => String.t | nil,
    :gtin => String.t | nil,
    :height => String.t | nil,
    :imageLink => String.t | nil,
    :images => any() | nil,
    :isTaxable => boolean() | nil,
    :length => String.t | nil,
    :link => String.t | nil,
    :maxStock => integer() | nil,
    :minStock => integer() | nil,
    :mpn => String.t | nil,
    :name => String.t | nil,
    :packageHeight => String.t | nil,
    :packageLength => String.t | nil,
    :packageWeightUnit => String.t | nil,
    :packageWeightValue => String.t | nil,
    :packageWidth => String.t | nil,
    :productCode => String.t | nil,
    :productType => String.t | nil,
    :purchasePrice => String.t | nil,
    :reorderQuantity => integer() | nil,
    :salePrice => String.t | nil,
    :shippingPrice => String.t | nil,
    :shippingRequiresInsurance => boolean() | nil,
    :sku => String.t | nil,
    :stockQuantity => integer() | nil,
    :tags => any() | nil,
    :taxPrice => String.t | nil,
    :trackBatch => boolean() | nil,
    :trackSerial => boolean() | nil,
    :unit => any() | nil,
    :weightUnit => String.t | nil,
    :weightValue => String.t | nil,
    :width => String.t | nil
  }

  def decode(value) do
    value
  end
end

