# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ProformaInvoice do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :convertedAt,
    :convertedToInvoiceId,
    :currency,
    :customerId,
    :customerSnapshot,
    :issueDate,
    :lineItems,
    :notes,
    :orderNumber,
    :paymentDueDate,
    :quotationId,
    :status,
    :subtotal,
    :totalAmount,
    :totalTax
  ]

  @type t :: %__MODULE__{
    :convertedAt => DateTime.t | nil,
    :convertedToInvoiceId => String.t | nil,
    :currency => SimpleBillyAPI.Model.CurrencyCode.t,
    :customerId => String.t | nil,
    :customerSnapshot => any() | nil,
    :issueDate => Date.t,
    :lineItems => any() | nil,
    :notes => String.t | nil,
    :orderNumber => String.t | nil,
    :paymentDueDate => Date.t | nil,
    :quotationId => String.t | nil,
    :status => SimpleBillyAPI.Model.ProformaInvoiceStatus.t,
    :subtotal => String.t,
    :totalAmount => String.t,
    :totalTax => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:currency, :struct, SimpleBillyAPI.Model.CurrencyCode)
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.ProformaInvoiceStatus)
  end
end

