# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PublicPosting do
  @moduledoc """
  Minimal shape for the public careers page (no tenant internals).
  """

  @derive JSON.Encoder
  defstruct [
    :currency,
    :description,
    :employmentType,
    :id,
    :location,
    :remote,
    :requiredSkills,
    :requirements,
    :salaryMax,
    :salaryMin,
    :title
  ]

  @type t :: %__MODULE__{
    :currency => String.t | nil,
    :description => String.t,
    :employmentType => String.t | nil,
    :id => String.t,
    :location => String.t | nil,
    :remote => boolean(),
    :requiredSkills => [String.t],
    :requirements => String.t | nil,
    :salaryMax => integer() | nil,
    :salaryMin => integer() | nil,
    :title => String.t
  }

  def decode(value) do
    value
  end
end

