# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.PublicDeliveryAppointmentRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :notes,
    :requestedDate,
    :supplierName,
    :timeSlot,
    :warehouseCode
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :notes => String.t | nil,
    :requestedDate => Date.t,
    :supplierName => String.t,
    :timeSlot => String.t | nil,
    :warehouseCode => String.t
  }

  def decode(value) do
    value
  end
end

