# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.QrCodeResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :content_type,
    :qr_code_base64
  ]

  @type t :: %__MODULE__{
    :content_type => String.t,
    :qr_code_base64 => String.t
  }

  def decode(value) do
    value
  end
end

