# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.QuotaOverride do
  @moduledoc """
  Schema of the `tenants.quotas` JSON override column. Any field that is present overrides the plan-derived value.
  """

  @derive JSON.Encoder
  defstruct [
    :features,
    :max_connectors,
    :max_invoices_per_month,
    :max_users,
    :metered,
    :plan
  ]

  @type t :: %__MODULE__{
    :features => SimpleBillyAPI.Model.QuotaOverrideFeatures.t | nil,
    :max_connectors => integer() | nil,
    :max_invoices_per_month => integer() | nil,
    :max_users => integer() | nil,
    :metered => %{optional(String.t) => integer()} | nil,
    :plan => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:features, :struct, SimpleBillyAPI.Model.QuotaOverrideFeatures)
  end
end

