# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.QuotaOverrideFeatures do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :erp,
    :fancy_reports,
    :tax_automations
  ]

  @type t :: %__MODULE__{
    :erp => boolean() | nil,
    :fancy_reports => boolean() | nil,
    :tax_automations => boolean() | nil
  }

  def decode(value) do
    value
  end
end

