# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.RateRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :customer,
    :packages,
    :recipient,
    :sender
  ]

  @type t :: %__MODULE__{
    :customer => SimpleBillyAPI.Model.CustomerInfo.t | nil,
    :packages => [SimpleBillyAPI.Model.Package.t],
    :recipient => SimpleBillyAPI.Model.Address.t,
    :sender => SimpleBillyAPI.Model.Address.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:customer, :struct, SimpleBillyAPI.Model.CustomerInfo)
     |> Deserializer.deserialize(:packages, :list, SimpleBillyAPI.Model.Package)
     |> Deserializer.deserialize(:recipient, :struct, SimpleBillyAPI.Model.Address)
     |> Deserializer.deserialize(:sender, :struct, SimpleBillyAPI.Model.Address)
  end
end

