# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.RateResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :rates
  ]

  @type t :: %__MODULE__{
    :rates => [SimpleBillyAPI.Model.ShippingRate.t]
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:rates, :list, SimpleBillyAPI.Model.ShippingRate)
  end
end

