# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.RecurringTemplateUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :endDate,
    :executionInterval,
    :executionStatus,
    :finalize,
    :lastExecutedAt,
    :name,
    :nextExecutionAt,
    :startDate,
    :templateType,
    :voucherData
  ]

  @type t :: %__MODULE__{
    :endDate => Date.t | nil,
    :executionInterval => String.t | nil,
    :executionStatus => SimpleBillyAPI.Model.ExecutionStatus.t | nil,
    :finalize => boolean() | nil,
    :lastExecutedAt => DateTime.t | nil,
    :name => String.t | nil,
    :nextExecutionAt => DateTime.t | nil,
    :startDate => Date.t | nil,
    :templateType => SimpleBillyAPI.Model.RecurringTemplateType.t | nil,
    :voucherData => any() | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:executionStatus, :struct, SimpleBillyAPI.Model.ExecutionStatus)
     |> Deserializer.deserialize(:templateType, :struct, SimpleBillyAPI.Model.RecurringTemplateType)
  end
end

