# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ReorderProposalResponse do
  @moduledoc """
  The response envelope for a reorder proposal run.
  """

  @derive JSON.Encoder
  defstruct [
    :generatedAt,
    :lines,
    :totalSuggestedQuantity
  ]

  @type t :: %__MODULE__{
    :generatedAt => DateTime.t,
    :lines => [SimpleBillyAPI.Model.ReorderProposalLine.t],
    :totalSuggestedQuantity => integer()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:lines, :list, SimpleBillyAPI.Model.ReorderProposalLine)
  end
end

