# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ReplenishmentResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :generatedAt,
    :lines,
    :targetWarehouseId,
    :totalSuggestedQuantity
  ]

  @type t :: %__MODULE__{
    :generatedAt => DateTime.t,
    :lines => [SimpleBillyAPI.Model.ReplenishmentSuggestionLine.t],
    :targetWarehouseId => String.t,
    :totalSuggestedQuantity => integer()
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:lines, :list, SimpleBillyAPI.Model.ReplenishmentSuggestionLine)
  end
end

