# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ReturnOrder do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :customerContactId,
    :customerName,
    :lineItems,
    :notes,
    :orderId,
    :orderNumber,
    :returnNumber,
    :returnReason,
    :status,
    :warehouseId
  ]

  @type t :: %__MODULE__{
    :customerContactId => String.t | nil,
    :customerName => String.t | nil,
    :lineItems => any() | nil,
    :notes => String.t | nil,
    :orderId => String.t | nil,
    :orderNumber => String.t | nil,
    :returnNumber => String.t,
    :returnReason => String.t | nil,
    :status => SimpleBillyAPI.Model.ReturnOrderStatus.t,
    :warehouseId => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.ReturnOrderStatus)
  end
end

