# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ReturnOrderStatusUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :status
  ]

  @type t :: %__MODULE__{
    :status => String.t
  }

  def decode(value) do
    value
  end
end

