# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.RevenueItem do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :amount,
    :category,
    :percentage
  ]

  @type t :: %__MODULE__{
    :amount => String.t,
    :category => String.t,
    :percentage => float()
  }

  def decode(value) do
    value
  end
end

