# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.RfqCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :currency,
    :lineItems,
    :notes,
    :requestedDate,
    :responseDate,
    :rfqNumber,
    :status,
    :supplierContactId,
    :supplierName
  ]

  @type t :: %__MODULE__{
    :currency => String.t | nil,
    :lineItems => any() | nil,
    :notes => String.t | nil,
    :requestedDate => Date.t,
    :responseDate => Date.t | nil,
    :rfqNumber => String.t,
    :status => SimpleBillyAPI.Model.RfqStatus.t,
    :supplierContactId => String.t | nil,
    :supplierName => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.RfqStatus)
  end
end

