# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.Section do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :bodyHtml,
    :bodyHtmlEn,
    :id,
    :title,
    :titleEn
  ]

  @type t :: %__MODULE__{
    :bodyHtml => String.t,
    :bodyHtmlEn => String.t,
    :id => String.t,
    :title => String.t,
    :titleEn => String.t
  }

  def decode(value) do
    value
  end
end

