# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ServiceJobUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :address,
    :customerEmail,
    :customerId,
    :customerName,
    :customerPhone,
    :description,
    :estimatedDurationMinutes,
    :lat,
    :lng,
    :notes,
    :status
  ]

  @type t :: %__MODULE__{
    :address => String.t | nil,
    :customerEmail => String.t | nil,
    :customerId => String.t | nil,
    :customerName => String.t | nil,
    :customerPhone => String.t | nil,
    :description => String.t | nil,
    :estimatedDurationMinutes => integer() | nil,
    :lat => float() | nil,
    :lng => float() | nil,
    :notes => String.t | nil,
    :status => SimpleBillyAPI.Model.ServiceJobStatus.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.ServiceJobStatus)
  end
end

