# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ShippingRate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :breakdown,
    :carrier,
    :cross_border_surcharge,
    :destination_country,
    :estimated_days,
    :from_api,
    :insured_value,
    :island_surcharge,
    :origin_country,
    :rate,
    :service,
    :volume_discount,
    :weight_kg
  ]

  @type t :: %__MODULE__{
    :breakdown => String.t | nil,
    :carrier => String.t,
    :cross_border_surcharge => String.t | nil,
    :destination_country => String.t,
    :estimated_days => integer() | nil,
    :from_api => boolean(),
    :insured_value => String.t | nil,
    :island_surcharge => String.t | nil,
    :origin_country => String.t,
    :rate => String.t,
    :service => String.t,
    :volume_discount => String.t | nil,
    :weight_kg => float()
  }

  def decode(value) do
    value
  end
end

