# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.Shipment do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :deliveredAt,
    :labelUrl,
    :lineItemsShipment,
    :orderId,
    :recipientAddress,
    :shipmentDate,
    :shippingCarrier,
    :shippingCost,
    :shippingMethod,
    :signedBy,
    :status,
    :trackingEvents,
    :trackingNumber,
    :trackingUrl,
    :weightKg
  ]

  @type t :: %__MODULE__{
    :deliveredAt => DateTime.t | nil,
    :labelUrl => String.t | nil,
    :lineItemsShipment => any() | nil,
    :orderId => String.t,
    :recipientAddress => any() | nil,
    :shipmentDate => Date.t,
    :shippingCarrier => String.t,
    :shippingCost => String.t | nil,
    :shippingMethod => String.t | nil,
    :signedBy => String.t | nil,
    :status => String.t,
    :trackingEvents => any() | nil,
    :trackingNumber => String.t | nil,
    :trackingUrl => String.t | nil,
    :weightKg => float() | nil
  }

  def decode(value) do
    value
  end
end

