# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ShippingThresholdUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :isActive,
    :maxSellable,
    :name,
    :notes,
    :productId,
    :reserveStock,
    :warehouseId
  ]

  @type t :: %__MODULE__{
    :isActive => boolean() | nil,
    :maxSellable => integer() | nil,
    :name => String.t | nil,
    :notes => String.t | nil,
    :productId => String.t | nil,
    :reserveStock => integer() | nil,
    :warehouseId => String.t | nil
  }

  def decode(value) do
    value
  end
end

