# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ShippingRuleCreate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :carrier,
    :country,
    :deliveryTime,
    :isActive,
    :maxWeightKg,
    :minWeightKg,
    :name,
    :notes,
    :price,
    :priority
  ]

  @type t :: %__MODULE__{
    :carrier => String.t | nil,
    :country => SimpleBillyAPI.Model.CountryCode.t | nil,
    :deliveryTime => String.t | nil,
    :isActive => boolean() | nil,
    :maxWeightKg => float() | nil,
    :minWeightKg => float() | nil,
    :name => String.t,
    :notes => String.t | nil,
    :price => String.t,
    :priority => integer() | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:country, :struct, SimpleBillyAPI.Model.CountryCode)
  end
end

