# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.ShippingCredentials do
  @moduledoc """
  Per-tenant credentials for real shipping provider APIs (stored in the `shipping` key of the settings JSON blob). Auth is either OAuth client credentials (UPS) or a user-supplied API key (DHL).
  """

  @derive JSON.Encoder
  defstruct [
    :dhl,
    :ups
  ]

  @type t :: %__MODULE__{
    :dhl => SimpleBillyAPI.Model.DhlCredentials.t | nil,
    :ups => SimpleBillyAPI.Model.UpsCredentials.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:dhl, :struct, SimpleBillyAPI.Model.DhlCredentials)
     |> Deserializer.deserialize(:ups, :struct, SimpleBillyAPI.Model.UpsCredentials)
  end
end

