# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.SmtpConfig do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :encryption,
    :from_address,
    :from_name,
    :host,
    :password,
    :port,
    :timeout_seconds,
    :username
  ]

  @type t :: %__MODULE__{
    :encryption => SimpleBillyAPI.Model.SmtpEncryption.t,
    :from_address => String.t,
    :from_name => String.t | nil,
    :host => String.t,
    :password => String.t,
    :port => integer(),
    :timeout_seconds => integer() | nil,
    :username => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:encryption, :struct, SimpleBillyAPI.Model.SmtpEncryption)
  end
end

