# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.StillePartnerZeile do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :auseinandersetzungsguthaben,
    :gewinnanteil,
    :gewinnvortrag,
    :hinweis,
    :instrument_type,
    :kest,
    :name,
    :verlust_verrechnungskonto,
    :verlustanteil
  ]

  @type t :: %__MODULE__{
    :auseinandersetzungsguthaben => String.t,
    :gewinnanteil => String.t,
    :gewinnvortrag => String.t,
    :hinweis => String.t | nil,
    :instrument_type => String.t,
    :kest => String.t,
    :name => String.t,
    :verlust_verrechnungskonto => String.t,
    :verlustanteil => String.t
  }

  def decode(value) do
    value
  end
end

