# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.StockMovement do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :delta,
    :movementType,
    :productId,
    :quantity,
    :reason,
    :referenceId,
    :referenceType,
    :warehouseId
  ]

  @type t :: %__MODULE__{
    :delta => integer(),
    :movementType => SimpleBillyAPI.Model.MovementType.t,
    :productId => String.t,
    :quantity => integer(),
    :reason => String.t | nil,
    :referenceId => String.t | nil,
    :referenceType => SimpleBillyAPI.Model.ReferenceType.t | nil,
    :warehouseId => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:movementType, :struct, SimpleBillyAPI.Model.MovementType)
     |> Deserializer.deserialize(:referenceType, :struct, SimpleBillyAPI.Model.ReferenceType)
  end
end

