# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.SupportTicketUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :assignedTo,
    :channelId,
    :channelType,
    :closedAt,
    :createdAt,
    :customerEmail,
    :customerId,
    :customerName,
    :externalId,
    :firstMessageAt,
    :lastMessageAt,
    :leadId,
    :messageCount,
    :orderRef,
    :priority,
    :resolution,
    :status,
    :subject,
    :tags,
    :tenantId,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :assignedTo => String.t | nil,
    :channelId => String.t | nil,
    :channelType => SimpleBillyAPI.Model.SupportChannelType.t | nil,
    :closedAt => DateTime.t | nil,
    :createdAt => DateTime.t | nil,
    :customerEmail => String.t | nil,
    :customerId => String.t | nil,
    :customerName => String.t | nil,
    :externalId => String.t | nil,
    :firstMessageAt => DateTime.t | nil,
    :lastMessageAt => DateTime.t | nil,
    :leadId => String.t | nil,
    :messageCount => integer() | nil,
    :orderRef => String.t | nil,
    :priority => SimpleBillyAPI.Model.TicketPriority.t | nil,
    :resolution => String.t | nil,
    :status => SimpleBillyAPI.Model.SupportTicketStatus.t | nil,
    :subject => String.t | nil,
    :tags => any() | nil,
    :tenantId => String.t | nil,
    :updatedAt => DateTime.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:channelType, :struct, SimpleBillyAPI.Model.SupportChannelType)
     |> Deserializer.deserialize(:priority, :struct, SimpleBillyAPI.Model.TicketPriority)
     |> Deserializer.deserialize(:status, :struct, SimpleBillyAPI.Model.SupportTicketStatus)
  end
end

