# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.TargetProgress do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :base_value,
    :base_year,
    :description,
    :id,
    :progress_pct,
    :scope,
    :target_value,
    :target_year
  ]

  @type t :: %__MODULE__{
    :base_value => float(),
    :base_year => integer(),
    :description => String.t,
    :id => String.t,
    :progress_pct => float() | nil,
    :scope => String.t,
    :target_value => float(),
    :target_year => integer()
  }

  def decode(value) do
    value
  end
end

