# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.TenantSettings do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :companyType,
    :dpaAcceptedAt,
    :dpaAcceptedBy,
    :dpaVersion,
    :features
  ]

  @type t :: %__MODULE__{
    :companyType => SimpleBillyAPI.Model.CompanyType.t,
    :dpaAcceptedAt => DateTime.t | nil,
    :dpaAcceptedBy => String.t | nil,
    :dpaVersion => String.t | nil,
    :features => any() | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:companyType, :struct, SimpleBillyAPI.Model.CompanyType)
  end
end

