# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.TenantUser do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :email_verified,
    :is_active,
    :joined_at,
    :last_login,
    :name,
    :permissions,
    :role,
    :user_id
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :email_verified => boolean(),
    :is_active => boolean(),
    :joined_at => DateTime.t,
    :last_login => DateTime.t | nil,
    :name => String.t,
    :permissions => [String.t],
    :role => String.t,
    :user_id => String.t
  }

  def decode(value) do
    value
  end
end

