# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.TimeEntryClockOut do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :clock_out,
    :hours
  ]

  @type t :: %__MODULE__{
    :clock_out => DateTime.t,
    :hours => String.t | nil
  }

  def decode(value) do
    value
  end
end

