# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.TrackOrderResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :order_number,
    :order_status,
    :shipments
  ]

  @type t :: %__MODULE__{
    :order_number => String.t,
    :order_status => String.t,
    :shipments => [SimpleBillyAPI.Model.TrackedShipment.t]
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:shipments, :list, SimpleBillyAPI.Model.TrackedShipment)
  end
end

