# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.TrackOrderRequest do
  @moduledoc """
  Refresh tracking for a shipment from the live carrier API and store the latest status + events on the shipment row.
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :order_number
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :order_number => String.t
  }

  def decode(value) do
    value
  end
end

