# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.TrackedShipment do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :carrier,
    :events,
    :label_url,
    :status,
    :tracking_number,
    :tracking_url
  ]

  @type t :: %__MODULE__{
    :carrier => String.t,
    :events => [SimpleBillyAPI.Model.TrackingEvent.t],
    :label_url => String.t | nil,
    :status => String.t,
    :tracking_number => String.t | nil,
    :tracking_url => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:events, :list, SimpleBillyAPI.Model.TrackingEvent)
  end
end

