# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.TrackingInfo do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :carrier,
    :estimated_delivery,
    :events,
    :raw_response,
    :status,
    :tracking_number
  ]

  @type t :: %__MODULE__{
    :carrier => String.t,
    :estimated_delivery => String.t | nil,
    :events => [SimpleBillyAPI.Model.TrackingEvent.t],
    :raw_response => any() | nil,
    :status => String.t,
    :tracking_number => String.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:events, :list, SimpleBillyAPI.Model.TrackingEvent)
  end
end

