# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.UpdateSyncDirectionRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :directions
  ]

  @type t :: %__MODULE__{
    :directions => %{optional(String.t) => String.t}
  }

  def decode(value) do
    value
  end
end

