# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.UpdateConnectionRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :api_key,
    :api_secret,
    :config,
    :is_active,
    :label,
    :shop_domain
  ]

  @type t :: %__MODULE__{
    :api_key => String.t | nil,
    :api_secret => String.t | nil,
    :config => any() | nil,
    :is_active => boolean() | nil,
    :label => String.t | nil,
    :shop_domain => String.t | nil
  }

  def decode(value) do
    value
  end
end

