# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.UpdateRolePayload do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :role,
    :sync_permissions
  ]

  @type t :: %__MODULE__{
    :role => String.t,
    :sync_permissions => boolean() | nil
  }

  def decode(value) do
    value
  end
end

