# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.UpdateProfileRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :avatar_url,
    :first_name,
    :last_name,
    :name
  ]

  @type t :: %__MODULE__{
    :avatar_url => String.t | nil,
    :first_name => String.t | nil,
    :last_name => String.t | nil,
    :name => String.t | nil
  }

  def decode(value) do
    value
  end
end

