# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.UpdateTenantSettings do
  @moduledoc """
  Request payload for updating tenant settings.
  """

  @derive JSON.Encoder
  defstruct [
    :companyType,
    :features
  ]

  @type t :: %__MODULE__{
    :companyType => SimpleBillyAPI.Model.CompanyType.t,
    :features => SimpleBillyAPI.Model.PartialFeatureSettings.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:companyType, :struct, SimpleBillyAPI.Model.CompanyType)
     |> Deserializer.deserialize(:features, :struct, SimpleBillyAPI.Model.PartialFeatureSettings)
  end
end

