# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.UpdateAutomation do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :config,
    :enabled
  ]

  @type t :: %__MODULE__{
    :config => any() | nil,
    :enabled => boolean() | nil
  }

  def decode(value) do
    value
  end
end

