# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.UpdateChannelDto do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :config,
    :is_active,
    :name
  ]

  @type t :: %__MODULE__{
    :config => any() | nil,
    :is_active => boolean() | nil,
    :name => String.t | nil
  }

  def decode(value) do
    value
  end
end

