# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.VatItem do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :net_amount,
    :tax_amount,
    :tax_rate
  ]

  @type t :: %__MODULE__{
    :net_amount => String.t,
    :tax_amount => String.t,
    :tax_rate => String.t
  }

  def decode(value) do
    value
  end
end

