# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.Voucher do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :categoryId,
    :contactId,
    :contactName,
    :currency,
    :description,
    :fileAttachments,
    :lineItems,
    :metadata,
    :notes,
    :openAmount,
    :paidDate,
    :paymentStatus,
    :taxAmounts,
    :taxCondition,
    :totalGrossAmount,
    :totalNetAmount,
    :voucherDate,
    :voucherNumber,
    :voucherStatus,
    :voucherType
  ]

  @type t :: %__MODULE__{
    :categoryId => String.t | nil,
    :contactId => String.t | nil,
    :contactName => String.t | nil,
    :currency => String.t,
    :description => String.t | nil,
    :fileAttachments => any() | nil,
    :lineItems => any() | nil,
    :metadata => any() | nil,
    :notes => String.t | nil,
    :openAmount => String.t | nil,
    :paidDate => Date.t | nil,
    :paymentStatus => SimpleBillyAPI.Model.PaymentStatus.t | nil,
    :taxAmounts => any() | nil,
    :taxCondition => String.t | nil,
    :totalGrossAmount => String.t | nil,
    :totalNetAmount => String.t | nil,
    :voucherDate => Date.t,
    :voucherNumber => String.t | nil,
    :voucherStatus => SimpleBillyAPI.Model.VoucherStatus.t,
    :voucherType => SimpleBillyAPI.Model.VoucherType.t
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:paymentStatus, :struct, SimpleBillyAPI.Model.PaymentStatus)
     |> Deserializer.deserialize(:voucherStatus, :struct, SimpleBillyAPI.Model.VoucherStatus)
     |> Deserializer.deserialize(:voucherType, :struct, SimpleBillyAPI.Model.VoucherType)
  end
end

