# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.WarehouseStock do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :batchNumber,
    :binLocation,
    :expiryDate,
    :productId,
    :quantity,
    :serialNumbers,
    :warehouseId
  ]

  @type t :: %__MODULE__{
    :batchNumber => String.t | nil,
    :binLocation => String.t | nil,
    :expiryDate => Date.t | nil,
    :productId => String.t,
    :quantity => integer(),
    :serialNumbers => any() | nil,
    :warehouseId => String.t
  }

  def decode(value) do
    value
  end
end

