# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.WarehouseUpdate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :addressCity,
    :addressCountry,
    :addressStreet,
    :addressZip,
    :binLocations,
    :code,
    :isActive,
    :isDefault,
    :name,
    :notes
  ]

  @type t :: %__MODULE__{
    :addressCity => String.t | nil,
    :addressCountry => SimpleBillyAPI.Model.CountryCode.t | nil,
    :addressStreet => String.t | nil,
    :addressZip => String.t | nil,
    :binLocations => any() | nil,
    :code => String.t | nil,
    :isActive => boolean() | nil,
    :isDefault => boolean() | nil,
    :name => String.t | nil,
    :notes => String.t | nil
  }

  alias SimpleBillyAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:addressCountry, :struct, SimpleBillyAPI.Model.CountryCode)
  end
end

