# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.Workflow do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :actions,
    :enabled,
    :name,
    :triggerEvent
  ]

  @type t :: %__MODULE__{
    :actions => any() | nil,
    :enabled => boolean() | nil,
    :name => String.t,
    :triggerEvent => String.t
  }

  def decode(value) do
    value
  end
end

