# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Model.WorkflowAction do
  @moduledoc """
  One action inside a workflow. Only `email` is supported for now.
  """

  @derive JSON.Encoder
  defstruct [
    :action_type,
    :body,
    :subject
  ]

  @type t :: %__MODULE__{
    :action_type => String.t,
    :body => String.t | nil,
    :subject => String.t | nil
  }

  def decode(value) do
    value
  end
end

