# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Ai do
  @moduledoc """
  API calls for all endpoints tagged `Ai`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `ai_suggestion_request` (AiSuggestionRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.AiSuggestion.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec ai_suggest_api(Tesla.Env.client, SimpleBillyAPI.Model.AiSuggestionRequest.t, keyword()) :: {:ok, SimpleBillyAPI.Model.AiSuggestion.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def ai_suggest_api(connection, ai_suggestion_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/support/ai/suggest")
      |> add_param(:body, :body, ai_suggestion_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.AiSuggestion},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `ai_config_dto` (AiConfigDto): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.AiWorkerConfig.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_worker_api(Tesla.Env.client, SimpleBillyAPI.Model.AiConfigDto.t, keyword()) :: {:ok, SimpleBillyAPI.Model.AiWorkerConfig.t} | {:error, Tesla.Env.t}
  def create_worker_api(connection, ai_config_dto, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/support/ai/workers")
      |> add_param(:body, :body, ai_config_dto)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.AiWorkerConfig}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%AiWorkerConfig{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_workers_api(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.AiWorkerConfig.t]} | {:error, Tesla.Env.t}
  def list_workers_api(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/support/ai/workers")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.AiWorkerConfig}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `worker_id` (String.t): 
  - `ai_suggestion_request` (AiSuggestionRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.AiSuggestion.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec run_worker_api(Tesla.Env.client, String.t, SimpleBillyAPI.Model.AiSuggestionRequest.t, keyword()) :: {:ok, SimpleBillyAPI.Model.AiSuggestion.t} | {:error, Tesla.Env.t}
  def run_worker_api(connection, worker_id, ai_suggestion_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/support/ai/workers/#{worker_id}/run")
      |> add_param(:body, :body, ai_suggestion_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.AiSuggestion}
    ])
  end
end
