# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Bom do
  @moduledoc """
  API calls for all endpoints tagged `Bom`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `bom_create` (BomCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Bom.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_bom(Tesla.Env.client, SimpleBillyAPI.Model.BomCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.Bom.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_bom(connection, bom_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/boms")
      |> add_param(:body, :body, bom_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.Bom},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `bom_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_bom(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_bom(connection, bom_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/boms/#{bom_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `bom_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Bom.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_bom(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.Bom.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_bom(connection, bom_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/boms/#{bom_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Bom},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:pageSize` (integer()): 
    - `:search` (String.t): 
    - `:productId` (String.t): Filter by finished product id.

  ### Returns

  - `{:ok, [%Bom{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_boms(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.Bom.t]} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def list_boms(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :pageSize => :query,
      :search => :query,
      :productId => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/boms/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Bom},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `bom_id` (String.t): 
  - `bom_update` (BomUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Bom.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_bom(Tesla.Env.client, String.t, SimpleBillyAPI.Model.BomUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.Bom.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_bom(connection, bom_id, bom_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/boms/#{bom_id}")
      |> add_param(:body, :body, bom_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Bom},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
