# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Bookkeeping do
  @moduledoc """
  API calls for all endpoints tagged `Bookkeeping`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """
  Allocate a payment to an invoice

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `allocate_payment_request` (AllocatePaymentRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec allocate_payment_api(Tesla.Env.client, SimpleBillyAPI.Model.AllocatePaymentRequest.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def allocate_payment_api(connection, allocate_payment_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/payments/allocate")
      |> add_param(:body, :body, allocate_payment_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """
  Get BWA (Betriebswirtschaftliche Auswertung) report

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:year` (integer()): 
    - `:month` (integer()): 

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.BwaReport.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec bwa_report_api(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.BwaReport.t} | {:error, Tesla.Env.t}
  def bwa_report_api(connection, opts \\ []) do
    optional_params = %{
      :year => :query,
      :month => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/bookkeeping/bwa")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.BwaReport},
      {500, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ElsterStatus.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec elster_status_api(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.ElsterStatus.t} | {:error, Tesla.Env.t}
  def elster_status_api(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/bookkeeping/elster/status")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ElsterStatus}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `zeitraum` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec elster_validate_api(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def elster_validate_api(connection, zeitraum, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/bookkeeping/ustva/elster-validate")
      |> add_param(:query, :zeitraum, zeitraum)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `zeitraum` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec elster_xml_api(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def elster_xml_api(connection, zeitraum, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/bookkeeping/ustva/elster-xml")
      |> add_param(:query, :zeitraum, zeitraum)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  GET /api/v1/bookkeeping/cashflow Returns operating, investing, and financing cashflow for the given period.

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:year` (integer()): 
    - `:month` (integer()): 

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.CashflowReport.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_cashflow(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.CashflowReport.t} | {:error, Tesla.Env.t}
  def get_cashflow(connection, opts \\ []) do
    optional_params = %{
      :year => :query,
      :month => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/bookkeeping/cashflow")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.CashflowReport},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """
  GET /api/v1/bookkeeping/liquidity Returns current liquidity position with ratios.

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.LiquidityPosition.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_liquidity(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.LiquidityPosition.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_liquidity(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/bookkeeping/liquidity")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.LiquidityPosition},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """
  Get open invoices for a customer

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `customer_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%Invoice{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_open_invoices_api(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.Invoice.t]} | {:error, Tesla.Env.t}
  def get_open_invoices_api(connection, customer_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/payments/open-invoices/#{customer_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Invoice},
      {404, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """
  GET /api/v1/bookkeeping/verfahrensdokumentation Returns the complete compliance catalog of all documented modules.

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Verfahrensdokumentation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_verfahrensdokumentation(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.Verfahrensdokumentation.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_verfahrensdokumentation(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/bookkeeping/verfahrensdokumentation")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Verfahrensdokumentation},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.DunningResult.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec run_dunning_api(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.DunningResult.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def run_dunning_api(connection, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/bookkeeping/dunning")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.DunningResult},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
