# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.ComplianceTraining do
  @moduledoc """
  API calls for all endpoints tagged `ComplianceTraining`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `compliance_training_create` (ComplianceTrainingCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ComplianceTraining.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_compliance_training(Tesla.Env.client, SimpleBillyAPI.Model.ComplianceTrainingCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ComplianceTraining.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_compliance_training(connection, compliance_training_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/compliance-trainings")
      |> add_param(:body, :body, compliance_training_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.ComplianceTraining},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_compliance_training(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_compliance_training(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/compliance-trainings/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ComplianceTraining.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_compliance_training(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ComplianceTraining.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_compliance_training(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/compliance-trainings/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ComplianceTraining},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:search` (String.t): 
    - `:include_deleted` (boolean()): Soft-delete entities: set true to include rows with `deleted_at` set.

  ### Returns

  - `{:ok, [%ComplianceTraining{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_compliance_trainings(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.ComplianceTraining.t]} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_compliance_trainings(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :search => :query,
      :include_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/compliance-trainings/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ComplianceTraining},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `compliance_training_update` (ComplianceTrainingUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ComplianceTraining.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_compliance_training(Tesla.Env.client, String.t, SimpleBillyAPI.Model.ComplianceTrainingUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ComplianceTraining.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_compliance_training(connection, id, compliance_training_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/compliance-trainings/#{id}")
      |> add_param(:body, :body, compliance_training_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ComplianceTraining},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
