# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.CustomerCommunication do
  @moduledoc """
  API calls for all endpoints tagged `CustomerCommunication`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `customer_communication_create` (CustomerCommunicationCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.CustomerCommunication.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_communication(Tesla.Env.client, SimpleBillyAPI.Model.CustomerCommunicationCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.CustomerCommunication.t} | {:error, Tesla.Env.t}
  def create_communication(connection, customer_communication_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/communications")
      |> add_param(:body, :body, customer_communication_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.CustomerCommunication},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `communication_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.CustomerCommunication.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec customercommunication_restore(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.CustomerCommunication.t} | {:error, Tesla.Env.t}
  def customercommunication_restore(connection, communication_id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/communications/#{communication_id}/restore")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.CustomerCommunication},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `communication_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_communication(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_communication(connection, communication_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/communications/#{communication_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `communication_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.CustomerCommunication.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_communication(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.CustomerCommunication.t} | {:error, Tesla.Env.t}
  def get_communication(connection, communication_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/communications/#{communication_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.CustomerCommunication},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `contact_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ContactHistoryResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_contact_history(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ContactHistoryResponse.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_contact_history(connection, contact_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/contacts/#{contact_id}/communications")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ContactHistoryResponse},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:contact_id` (String.t): Filter history to a single contact.
    - `:channel` (SimpleBillyAPI.Model.CommunicationChannel.t): 
    - `:direction` (SimpleBillyAPI.Model.CommunicationDirection.t): 
    - `:from` (Date.t): Only include communications after this ISO date (inclusive).
    - `:to` (Date.t): Only include communications before this ISO date (inclusive).

  ### Returns

  - `{:ok, [%CustomerCommunication{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_communications(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.CustomerCommunication.t]} | {:error, Tesla.Env.t}
  def list_communications(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :contact_id => :query,
      :channel => :query,
      :direction => :query,
      :from => :query,
      :to => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/communications/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.CustomerCommunication},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `communication_id` (String.t): 
  - `customer_communication_update` (CustomerCommunicationUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.CustomerCommunication.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_communication(Tesla.Env.client, String.t, SimpleBillyAPI.Model.CustomerCommunicationUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.CustomerCommunication.t} | {:error, Tesla.Env.t}
  def update_communication(connection, communication_id, customer_communication_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/communications/#{communication_id}")
      |> add_param(:body, :body, customer_communication_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.CustomerCommunication},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
