# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.DeliveryDate do
  @moduledoc """
  API calls for all endpoints tagged `DeliveryDate`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `delivery_date_create` (DeliveryDateCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.DeliveryDate.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_delivery_date(Tesla.Env.client, SimpleBillyAPI.Model.DeliveryDateCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.DeliveryDate.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_delivery_date(connection, delivery_date_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/delivery-dates")
      |> add_param(:body, :body, delivery_date_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.DeliveryDate},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `delivery_date_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_delivery_date(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_delivery_date(connection, delivery_date_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/delivery-dates/#{delivery_date_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `delivery_date_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.DeliveryDate.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_delivery_date(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.DeliveryDate.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_delivery_date(connection, delivery_date_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/delivery-dates/#{delivery_date_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.DeliveryDate},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """
  On-time performance summary: how many promised delivery dates were met within a period.

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:pageSize` (integer()): 
    - `:orderNumber` (String.t): 
    - `:status` (String.t): 
    - `:from` (Date.t): Only dates on or after this date.
    - `:to` (Date.t): Only dates on or before this date.

  ### Returns

  - `{:ok, any()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_delivery_performance(Tesla.Env.client, keyword()) :: {:ok, any()} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_delivery_performance(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :pageSize => :query,
      :orderNumber => :query,
      :status => :query,
      :from => :query,
      :to => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/delivery-dates/performance")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:pageSize` (integer()): 
    - `:orderNumber` (String.t): 
    - `:status` (String.t): 
    - `:from` (Date.t): Only dates on or after this date.
    - `:to` (Date.t): Only dates on or before this date.

  ### Returns

  - `{:ok, [%DeliveryDate{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_delivery_dates(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.DeliveryDate.t]} | {:error, Tesla.Env.t}
  def list_delivery_dates(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :pageSize => :query,
      :orderNumber => :query,
      :status => :query,
      :from => :query,
      :to => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/delivery-dates/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.DeliveryDate},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `delivery_date_id` (String.t): 
  - `body` (any()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.DeliveryDate.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_delivery_date(Tesla.Env.client, String.t, any(), keyword()) :: {:ok, SimpleBillyAPI.Model.DeliveryDate.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_delivery_date(connection, delivery_date_id, body, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/delivery-dates/#{delivery_date_id}")
      |> add_param(:body, :body, body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.DeliveryDate},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `delivery_date_id` (String.t): 
  - `delivery_date_status_update` (DeliveryDateStatusUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.DeliveryDate.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_delivery_date_status(Tesla.Env.client, String.t, SimpleBillyAPI.Model.DeliveryDateStatusUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.DeliveryDate.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_delivery_date_status(connection, delivery_date_id, delivery_date_status_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/delivery-dates/#{delivery_date_id}/status")
      |> add_param(:body, :body, delivery_date_status_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.DeliveryDate},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
