# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.EmailTemplate do
  @moduledoc """
  API calls for all endpoints tagged `EmailTemplate`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `email_template_create` (EmailTemplateCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.EmailTemplate.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_email_template(Tesla.Env.client, SimpleBillyAPI.Model.EmailTemplateCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.EmailTemplate.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_email_template(connection, email_template_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/email-templates")
      |> add_param(:body, :body, email_template_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.EmailTemplate},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `email_template_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_email_template(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_email_template(connection, email_template_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/email-templates/#{email_template_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `email_template_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.EmailTemplate.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_email_template(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.EmailTemplate.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_email_template(connection, email_template_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/email-templates/#{email_template_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.EmailTemplate},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:pageSize` (integer()): 
    - `:status` (String.t): 
    - `:search` (String.t): 

  ### Returns

  - `{:ok, [%EmailTemplate{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_email_templates(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.EmailTemplate.t]} | {:error, Tesla.Env.t}
  def list_email_templates(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :pageSize => :query,
      :status => :query,
      :search => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/email-templates/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.EmailTemplate},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `email_template_id` (String.t): 
  - `body` (any()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, any()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec render_email_template(Tesla.Env.client, String.t, any(), keyword()) :: {:ok, any()} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def render_email_template(connection, email_template_id, body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/email-templates/#{email_template_id}/render")
      |> add_param(:body, :body, body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `email_template_id` (String.t): 
  - `email_template_update` (EmailTemplateUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.EmailTemplate.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_email_template(Tesla.Env.client, String.t, SimpleBillyAPI.Model.EmailTemplateUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.EmailTemplate.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_email_template(connection, email_template_id, email_template_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/email-templates/#{email_template_id}")
      |> add_param(:body, :body, email_template_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.EmailTemplate},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
