# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.EventSubscription do
  @moduledoc """
  API calls for all endpoints tagged `EventSubscription`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `body` (any()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.EventSubscription.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_event_subscription(Tesla.Env.client, any(), keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.EventSubscription.t} | {:error, Tesla.Env.t}
  def create_event_subscription(connection, body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/event-subscriptions")
      |> add_param(:body, :body, body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.EventSubscription},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `subscription_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_event_subscription(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_event_subscription(connection, subscription_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/event-subscriptions/#{subscription_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%EventSubscription{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_event_subscriptions(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.EventSubscription.t]} | {:error, Tesla.Env.t}
  def list_event_subscriptions(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/event-subscriptions/")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.EventSubscription},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
