# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.GroupFigure do
  @moduledoc """
  API calls for all endpoints tagged `GroupFigure`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `group_figure_create` (GroupFigureCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.GroupFigure.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_group_figure(Tesla.Env.client, SimpleBillyAPI.Model.GroupFigureCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.GroupFigure.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_group_figure(connection, group_figure_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/group-figures")
      |> add_param(:body, :body, group_figure_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.GroupFigure},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `year` (integer()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_group_figure(Tesla.Env.client, integer(), keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_group_figure(connection, year, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/group-figures/#{year}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `year` (integer()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.GroupFigure.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_group_figure(Tesla.Env.client, integer(), keyword()) :: {:ok, SimpleBillyAPI.Model.GroupFigure.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_group_figure(connection, year, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/group-figures/#{year}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.GroupFigure},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:search` (String.t): 
    - `:include_deleted` (boolean()): Soft-delete entities: set true to include rows with `deleted_at` set.

  ### Returns

  - `{:ok, [%GroupFigure{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_group_figures(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.GroupFigure.t]} | {:error, Tesla.Env.t}
  def get_group_figures(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :search => :query,
      :include_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/group-figures/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.GroupFigure},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `year` (integer()): 
  - `group_figure_update` (GroupFigureUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.GroupFigure.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_group_figure(Tesla.Env.client, integer(), SimpleBillyAPI.Model.GroupFigureUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.GroupFigure.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_group_figure(connection, year, group_figure_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/group-figures/#{year}")
      |> add_param(:body, :body, group_figure_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.GroupFigure},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
