# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.JobPosting do
  @moduledoc """
  API calls for all endpoints tagged `JobPosting`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `job_posting_create` (JobPostingCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.JobPosting.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_job_posting(Tesla.Env.client, SimpleBillyAPI.Model.JobPostingCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.JobPosting.t} | {:error, Tesla.Env.t}
  def create_job_posting(connection, job_posting_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/job-postings")
      |> add_param(:body, :body, job_posting_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.JobPosting},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_job_posting(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_job_posting(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/job-postings/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.JobPosting.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_job_posting(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.JobPosting.t} | {:error, Tesla.Env.t}
  def get_job_posting(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/job-postings/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.JobPosting},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:status` (String.t): 
    - `:page` (integer()): 
    - `:pageSize` (integer()): 

  ### Returns

  - `{:ok, [%JobPosting{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_job_postings(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.JobPosting.t]} | {:error, Tesla.Env.t}
  def list_job_postings(connection, opts \\ []) do
    optional_params = %{
      :status => :query,
      :page => :query,
      :pageSize => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/job-postings")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.JobPosting}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `job_posting_update` (JobPostingUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.JobPosting.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_job_posting(Tesla.Env.client, String.t, SimpleBillyAPI.Model.JobPostingUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.JobPosting.t} | {:error, Tesla.Env.t}
  def update_job_posting(connection, id, job_posting_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/job-postings/#{id}")
      |> add_param(:body, :body, job_posting_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.JobPosting},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
