# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.JobApplication do
  @moduledoc """
  API calls for all endpoints tagged `JobApplication`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `posting_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec apply_public(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def apply_public(connection, posting_id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/public/jobs/#{posting_id}/apply")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `application_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.JobApplication.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_job_application(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.JobApplication.t} | {:error, Tesla.Env.t}
  def delete_job_application(connection, application_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/job-applications/#{application_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.JobApplication}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `application_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec download_cv(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def download_cv(connection, application_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/job-applications/#{application_id}/cv")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `application_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.JobApplication.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_job_application(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.JobApplication.t} | {:error, Tesla.Env.t}
  def get_job_application(connection, application_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/job-applications/#{application_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.JobApplication}
    ])
  end

  @doc """
  Inbound CV email, mailgun/sendgrid inbound-parse style: multipart form with `from`, `subject`, `body-plain` and one or more `attachment-N` file fields. The subject may reference a posting as `[JOB-<posting_id>]`; without one the application lands in the general inbox.

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec inbound_email(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def inbound_email(connection, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/public/jobs/inbound-email")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:postingId` (String.t): 
    - `:status` (String.t): 
    - `:page` (integer()): 
    - `:pageSize` (integer()): 

  ### Returns

  - `{:ok, [%JobApplication{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_job_applications(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.JobApplication.t]} | {:error, Tesla.Env.t}
  def list_job_applications(connection, opts \\ []) do
    optional_params = %{
      :postingId => :query,
      :status => :query,
      :page => :query,
      :pageSize => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/job-applications")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.JobApplication}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%PublicPosting{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_public_postings(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.PublicPosting.t]} | {:error, Tesla.Env.t}
  def list_public_postings(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/public/jobs")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PublicPosting}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `application_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.JobApplication.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec score_job_application(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.JobApplication.t} | {:error, Tesla.Env.t}
  def score_job_application(connection, application_id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/job-applications/#{application_id}/score")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.JobApplication}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `application_id` (String.t): 
  - `application_status_dto` (ApplicationStatusDto): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.JobApplication.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_job_application_status(Tesla.Env.client, String.t, SimpleBillyAPI.Model.ApplicationStatusDto.t, keyword()) :: {:ok, SimpleBillyAPI.Model.JobApplication.t} | {:error, Tesla.Env.t}
  def update_job_application_status(connection, application_id, application_status_dto, _opts \\ []) do
    request =
      %{}
      |> method(:patch)
      |> url("/api/v1/job-applications/#{application_id}/status")
      |> add_param(:body, :body, application_status_dto)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.JobApplication}
    ])
  end
end
