# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Notifications do
  @moduledoc """
  API calls for all endpoints tagged `Notifications`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_notification(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def delete_notification(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/notifications/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {404, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%NotificationDto{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_notifications(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.NotificationDto.t]} | {:error, Tesla.Env.t}
  def list_notifications(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/notifications")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.NotificationDto}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, integer()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec mark_all_read(Tesla.Env.client, keyword()) :: {:ok, integer()} | {:error, Tesla.Env.t}
  def mark_all_read(connection, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/notifications/read-all")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec mark_as_read(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def mark_as_read(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/notifications/#{id}/read")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {404, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, integer()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec unread_count(Tesla.Env.client, keyword()) :: {:ok, integer()} | {:error, Tesla.Env.t}
  def unread_count(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/notifications/unread-count")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
