# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Packing do
  @moduledoc """
  API calls for all endpoints tagged `Packing`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """
  Mark packing as complete and transition order to shipped

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `order_number` (String.t): 
  - `packing_complete_request` (PackingCompleteRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PackingCompleteResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec complete_packing(Tesla.Env.client, String.t, SimpleBillyAPI.Model.PackingCompleteRequest.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PackingCompleteResponse.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def complete_packing(connection, order_number, packing_complete_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/packing/#{order_number}/complete")
      |> add_param(:body, :body, packing_complete_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PackingCompleteResponse},
      {404, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """
  Get the packing queue - orders ready for packing

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:search` (String.t): 

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PackingQueue.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_packing_queue(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PackingQueue.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_packing_queue(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :search => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/packing/queue")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PackingQueue},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """
  Print delivery note (Lieferschein) for an order

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `order_number` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PrintDeliveryNoteResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec print_delivery_note(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.PrintDeliveryNoteResponse.t} | {:error, Tesla.Env.t}
  def print_delivery_note(connection, order_number, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/packing/#{order_number}/print-delivery-note")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PrintDeliveryNoteResponse},
      {404, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """
  Print shipping label for an order

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `order_number` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PrintLabelResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec print_label(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.PrintLabelResponse.t} | {:error, Tesla.Env.t}
  def print_label(connection, order_number, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/packing/#{order_number}/print-label")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PrintLabelResponse},
      {404, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """
  Record video of packing process

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `order_number` (String.t): 
  - `body` (any()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PackingVideoResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec record_packing_video(Tesla.Env.client, String.t, any(), keyword()) :: {:ok, SimpleBillyAPI.Model.PackingVideoResponse.t} | {:error, Tesla.Env.t}
  def record_packing_video(connection, order_number, body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/packing/#{order_number}/record-video")
      |> add_param(:body, :body, body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PackingVideoResponse}
    ])
  end
end
