# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Payroll do
  @moduledoc """
  API calls for all endpoints tagged `Payroll`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PayrollRunApi.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_approve(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PayrollRunApi.t} | {:error, Tesla.Env.t}
  def payroll_approve(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/payroll/#{id}/approve")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PayrollRunApi}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:body` (any()): 

  ### Returns

  - `{:ok, any()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_autopay(Tesla.Env.client, String.t, keyword()) :: {:ok, any()} | {:error, Tesla.Env.t}
  def payroll_autopay(connection, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/api/v1/payroll/#{id}/autopay")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PayrollRunApi.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_calculate(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PayrollRunApi.t} | {:error, Tesla.Env.t}
  def payroll_calculate(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/payroll/#{id}/calculate")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PayrollRunApi}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `payroll_create_payload` (PayrollCreatePayload): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PayrollRunApi.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_create(Tesla.Env.client, SimpleBillyAPI.Model.PayrollCreatePayload.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PayrollRunApi.t} | {:error, Tesla.Env.t}
  def payroll_create(connection, payroll_create_payload, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/payroll")
      |> add_param(:body, :body, payroll_create_payload)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.PayrollRunApi}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def payroll_delete(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/payroll/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_elster_export(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def payroll_elster_export(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/payroll/#{id}/elster-export")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, any()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_email(Tesla.Env.client, String.t, keyword()) :: {:ok, any()} | {:error, Tesla.Env.t}
  def payroll_email(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/payroll/#{id}/email")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `entry_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_entry_pdf(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def payroll_entry_pdf(connection, id, entry_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/payroll/#{id}/entries/#{entry_id}/pdf")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PayrollRunApi.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_get(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PayrollRunApi.t} | {:error, Tesla.Env.t}
  def payroll_get(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/payroll/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PayrollRunApi}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:year` (integer()): 
    - `:status` (String.t): 

  ### Returns

  - `{:ok, [%PayrollRunApi{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_list(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.PayrollRunApi.t]} | {:error, Tesla.Env.t}
  def payroll_list(connection, opts \\ []) do
    optional_params = %{
      :year => :query,
      :status => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/payroll")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PayrollRunApi}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `payroll_pay_payload` (PayrollPayPayload): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PayrollRunApi.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_pay(Tesla.Env.client, String.t, SimpleBillyAPI.Model.PayrollPayPayload.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PayrollRunApi.t} | {:error, Tesla.Env.t}
  def payroll_pay(connection, id, payroll_pay_payload, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/payroll/#{id}/pay")
      |> add_param(:body, :body, payroll_pay_payload)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PayrollRunApi}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_pdf(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def payroll_pdf(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/payroll/#{id}/pdf")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `year` (integer()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.YearlyPayrollSummary.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_summary(Tesla.Env.client, integer(), keyword()) :: {:ok, SimpleBillyAPI.Model.YearlyPayrollSummary.t} | {:error, Tesla.Env.t}
  def payroll_summary(connection, year, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/payroll/summary/#{year}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.YearlyPayrollSummary}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, any()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec payroll_sv_meldungen(Tesla.Env.client, String.t, keyword()) :: {:ok, any()} | {:error, Tesla.Env.t}
  def payroll_sv_meldungen(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/payroll/#{id}/sv-meldungen")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
