# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.PostingCategory do
  @moduledoc """
  API calls for all endpoints tagged `PostingCategory`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `body` (any()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PostingCategory.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_posting_category(Tesla.Env.client, any(), keyword()) :: {:ok, SimpleBillyAPI.Model.PostingCategory.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_posting_category(connection, body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/posting-categories")
      |> add_param(:body, :body, body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.PostingCategory},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `category_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_posting_category(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_posting_category(connection, category_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/posting-categories/#{category_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, false},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%PostingCategory{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_posting_categories(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.PostingCategory.t]} | {:error, Tesla.Env.t}
  def list_posting_categories(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/posting-categories")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PostingCategory},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `skr_version` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec seed_posting_categories(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def seed_posting_categories(connection, skr_version, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/posting-categories/seed/#{skr_version}")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `category_id` (String.t): 
  - `body` (any()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PostingCategory.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_posting_category(Tesla.Env.client, String.t, any(), keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PostingCategory.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_posting_category(connection, category_id, body, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/posting-categories/#{category_id}")
      |> add_param(:body, :body, body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PostingCategory},
      {404, false},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
