# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.PriceTier do
  @moduledoc """
  API calls for all endpoints tagged `PriceTier`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `price_tier_create` (PriceTierCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PriceTier.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_price_tier(Tesla.Env.client, SimpleBillyAPI.Model.PriceTierCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PriceTier.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_price_tier(connection, price_tier_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/price-tiers")
      |> add_param(:body, :body, price_tier_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.PriceTier},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `price_tier_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_price_tier(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_price_tier(connection, price_tier_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/price-tiers/#{price_tier_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `price_tier_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PriceTier.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_price_tier(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PriceTier.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_price_tier(connection, price_tier_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/price-tiers/#{price_tier_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PriceTier},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `product_id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:quantity` (integer()): 
    - `:contactId` (String.t): Contact used to match customer-group-scoped tiers.

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ResolvedPriceResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_resolved_price(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.ResolvedPriceResponse.t} | {:error, Tesla.Env.t}
  def get_resolved_price(connection, product_id, opts \\ []) do
    optional_params = %{
      :quantity => :query,
      :contactId => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/price-tiers/resolved")
      |> add_param(:query, :productId, product_id)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ResolvedPriceResponse},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:product_id` (String.t): 
    - `:customer_group_id` (String.t): 

  ### Returns

  - `{:ok, [%PriceTier{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_price_tiers(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.PriceTier.t]} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def list_price_tiers(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :product_id => :query,
      :customer_group_id => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/price-tiers/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PriceTier},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `price_tier_id` (String.t): 
  - `price_tier_update` (PriceTierUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.PriceTier.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_price_tier(Tesla.Env.client, String.t, SimpleBillyAPI.Model.PriceTierUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PriceTier.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_price_tier(connection, price_tier_id, price_tier_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/price-tiers/#{price_tier_id}")
      |> add_param(:body, :body, price_tier_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.PriceTier},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
