# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Product do
  @moduledoc """
  API calls for all endpoints tagged `Product`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `product_create` (ProductCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Product.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_product_api(Tesla.Env.client, SimpleBillyAPI.Model.ProductCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.Product.t} | {:error, Tesla.Env.t}
  def create_product_api(connection, product_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/products")
      |> add_param(:body, :body, product_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.Product},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `product_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_product_api(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_product_api(connection, product_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/products/#{product_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `product_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Product.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_product_api(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.Product.t} | {:error, Tesla.Env.t}
  def get_product_api(connection, product_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/products/#{product_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Product},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `product_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ProductStock.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_product_stock_api(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ProductStock.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_product_stock_api(connection, product_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/products/#{product_id}/stock")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductStock},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:search` (String.t): 
    - `:include_deleted` (boolean()): Soft-delete entities: set true to include rows with `deleted_at` set.

  ### Returns

  - `{:ok, [%Product{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_products_api(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.Product.t]} | {:error, Tesla.Env.t}
  def get_products_api(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :search => :query,
      :include_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/products/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Product},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:threshold` (integer()): 

  ### Returns

  - `{:ok, [%ProductStock{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_low_stock_products_api(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.ProductStock.t]} | {:error, Tesla.Env.t}
  def list_low_stock_products_api(connection, opts \\ []) do
    optional_params = %{
      :threshold => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/products/low-stock")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductStock},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `product_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Product.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec product_restore(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.Product.t} | {:error, Tesla.Env.t}
  def product_restore(connection, product_id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/products/#{product_id}/restore")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Product},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `product_id` (String.t): 
  - `product_update` (ProductUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Product.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_product_api(Tesla.Env.client, String.t, SimpleBillyAPI.Model.ProductUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.Product.t} | {:error, Tesla.Env.t}
  def update_product_api(connection, product_id, product_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/products/#{product_id}")
      |> add_param(:body, :body, product_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Product},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `product_id` (String.t): 
  - `stock_update_request` (StockUpdateRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ProductStock.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_product_stock_api(Tesla.Env.client, String.t, SimpleBillyAPI.Model.StockUpdateRequest.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ProductStock.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_product_stock_api(connection, product_id, stock_update_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/products/#{product_id}/stock")
      |> add_param(:body, :body, stock_update_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductStock},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
