# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.ProductionOrder do
  @moduledoc """
  API calls for all endpoints tagged `ProductionOrder`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `production_order` (ProductionOrder): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ProductionOrder.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_production_order(Tesla.Env.client, SimpleBillyAPI.Model.ProductionOrder.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ProductionOrder.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_production_order(connection, production_order, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/production-orders")
      |> add_param(:body, :body, production_order)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.ProductionOrder},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `production_order_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_production_order(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_production_order(connection, production_order_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/production-orders/#{production_order_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `production_order_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ProductionOrder.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_production_order(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ProductionOrder.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_production_order(connection, production_order_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/production-orders/#{production_order_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductionOrder},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:pageSize` (integer()): 
    - `:search` (String.t): 
    - `:status` (String.t): Filter by status.

  ### Returns

  - `{:ok, [%ProductionOrder{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_production_orders(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.ProductionOrder.t]} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def list_production_orders(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :pageSize => :query,
      :search => :query,
      :status => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/production-orders/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductionOrder},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """
  Actual-costing report (Nachkalkulation) — material costs from BOM components at their purchase price plus the resulting per-unit cost and margin against the finished product's sale price.

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `production_order_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ProductionOrderCosting.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec production_order_costing(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ProductionOrderCosting.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def production_order_costing(connection, production_order_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/production-orders/#{production_order_id}/costing")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductionOrderCosting},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `production_order_id` (String.t): 
  - `production_order` (ProductionOrder): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ProductionOrder.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_production_order(Tesla.Env.client, String.t, SimpleBillyAPI.Model.ProductionOrder.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ProductionOrder.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_production_order(connection, production_order_id, production_order, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/production-orders/#{production_order_id}")
      |> add_param(:body, :body, production_order)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductionOrder},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `production_order_id` (String.t): 
  - `production_order_status_update` (ProductionOrderStatusUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ProductionOrder.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_production_order_status(Tesla.Env.client, String.t, SimpleBillyAPI.Model.ProductionOrderStatusUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ProductionOrder.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_production_order_status(connection, production_order_id, production_order_status_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/production-orders/#{production_order_id}/status")
      |> add_param(:body, :body, production_order_status_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductionOrder},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
