# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.ProductAttribute do
  @moduledoc """
  API calls for all endpoints tagged `ProductAttribute`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `product_attribute_create` (ProductAttributeCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ProductAttribute.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_product_attribute(Tesla.Env.client, SimpleBillyAPI.Model.ProductAttributeCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ProductAttribute.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_product_attribute(connection, product_attribute_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/product-attributes")
      |> add_param(:body, :body, product_attribute_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.ProductAttribute},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `attribute_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_product_attribute(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_product_attribute(connection, attribute_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/product-attributes/#{attribute_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `attribute_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ProductAttribute.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_product_attribute(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ProductAttribute.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_product_attribute(connection, attribute_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/product-attributes/#{attribute_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductAttribute},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:product_id` (String.t): 
    - `:is_filterable` (boolean()): 
    - `:search` (String.t): 

  ### Returns

  - `{:ok, [%ProductAttribute{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_product_attributes(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.ProductAttribute.t]} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def list_product_attributes(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :product_id => :query,
      :is_filterable => :query,
      :search => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/product-attributes/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductAttribute},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `attribute_id` (String.t): 
  - `product_attribute_update` (ProductAttributeUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ProductAttribute.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_product_attribute(Tesla.Env.client, String.t, SimpleBillyAPI.Model.ProductAttributeUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ProductAttribute.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_product_attribute(connection, attribute_id, product_attribute_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/product-attributes/#{attribute_id}")
      |> add_param(:body, :body, product_attribute_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProductAttribute},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
