# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Quotation do
  @moduledoc """
  API calls for all endpoints tagged `Quotation`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `quotation_create` (QuotationCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Quotation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_quotation(Tesla.Env.client, SimpleBillyAPI.Model.QuotationCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.Quotation.t} | {:error, Tesla.Env.t}
  def create_quotation(connection, quotation_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/quotations")
      |> add_param(:body, :body, quotation_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.Quotation},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `quotation_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_quotation(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_quotation(connection, quotation_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/quotations/#{quotation_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `quotation_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec download_quotation_pdf(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def download_quotation_pdf(connection, quotation_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/quotations/#{quotation_id}/pdf")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `quotation_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Quotation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_quotation(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.Quotation.t} | {:error, Tesla.Env.t}
  def get_quotation(connection, quotation_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/quotations/#{quotation_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Quotation},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:search` (String.t): 
    - `:include_deleted` (boolean()): Soft-delete entities: set true to include rows with `deleted_at` set.

  ### Returns

  - `{:ok, [%Quotation{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_quotations(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.Quotation.t]} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def list_quotations(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :search => :query,
      :include_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/quotations/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Quotation},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `quotation_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.OrderConfirmation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec pursue_quotation(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.OrderConfirmation.t} | {:error, Tesla.Env.t}
  def pursue_quotation(connection, quotation_id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/quotations/#{quotation_id}/pursue")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.OrderConfirmation},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `quotation_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Quotation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec quotation_restore(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.Quotation.t} | {:error, Tesla.Env.t}
  def quotation_restore(connection, quotation_id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/quotations/#{quotation_id}/restore")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Quotation},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `quotation_id` (String.t): 
  - `body` (any()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Quotation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_quotation(Tesla.Env.client, String.t, any(), keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.Quotation.t} | {:error, Tesla.Env.t}
  def update_quotation(connection, quotation_id, body, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/quotations/#{quotation_id}")
      |> add_param(:body, :body, body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Quotation},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
