# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Rfq do
  @moduledoc """
  API calls for all endpoints tagged `Rfq`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """
  Convert an RFQ into a draft purchase order using the quoted unit prices (falling back to the requested prices, then leaving them blank). Marks the RFQ as `converted`.

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `rfq_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, any()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec convert_rfq(Tesla.Env.client, String.t, keyword()) :: {:ok, any()} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def convert_rfq(connection, rfq_id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/rfqs/#{rfq_id}/convert")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `rfq` (Rfq): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Rfq.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_rfq(Tesla.Env.client, SimpleBillyAPI.Model.Rfq.t, keyword()) :: {:ok, SimpleBillyAPI.Model.Rfq.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_rfq(connection, rfq, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/rfqs")
      |> add_param(:body, :body, rfq)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.Rfq},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `rfq_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_rfq(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_rfq(connection, rfq_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/rfqs/#{rfq_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `rfq_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Rfq.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_rfq(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.Rfq.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_rfq(connection, rfq_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/rfqs/#{rfq_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Rfq},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:status` (String.t): 
    - `:supplier_name` (String.t): 

  ### Returns

  - `{:ok, [%Rfq{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_rfqs(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.Rfq.t]} | {:error, Tesla.Env.t}
  def list_rfqs(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :status => :query,
      :supplier_name => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/rfqs/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Rfq},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `rfq_id` (String.t): 
  - `body` (any()): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Rfq.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_rfq(Tesla.Env.client, String.t, any(), keyword()) :: {:ok, SimpleBillyAPI.Model.Rfq.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_rfq(connection, rfq_id, body, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/rfqs/#{rfq_id}")
      |> add_param(:body, :body, body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Rfq},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `rfq_id` (String.t): 
  - `rfq_status_update` (RfqStatusUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.Rfq.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_rfq_status(Tesla.Env.client, String.t, SimpleBillyAPI.Model.RfqStatusUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.Rfq.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_rfq_status(connection, rfq_id, rfq_status_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/rfqs/#{rfq_id}/status")
      |> add_param(:body, :body, rfq_status_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.Rfq},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
