# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.ServiceJob do
  @moduledoc """
  API calls for all endpoints tagged `ServiceJob`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `service_job_create` (ServiceJobCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ServiceJob.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_service_job(Tesla.Env.client, SimpleBillyAPI.Model.ServiceJobCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ServiceJob.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_service_job(connection, service_job_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/service-jobs")
      |> add_param(:body, :body, service_job_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.ServiceJob},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_service_job(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_service_job(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/service-jobs/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ServiceJob.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_service_job(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ServiceJob.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_service_job(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/service-jobs/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ServiceJob},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:search` (String.t): 
    - `:include_deleted` (boolean()): Soft-delete entities: set true to include rows with `deleted_at` set.

  ### Returns

  - `{:ok, [%ServiceJob{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_service_jobs(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.ServiceJob.t]} | {:error, Tesla.Env.t}
  def get_service_jobs(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :search => :query,
      :include_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/service-jobs/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ServiceJob},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `service_job_update` (ServiceJobUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ServiceJob.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_service_job(Tesla.Env.client, String.t, SimpleBillyAPI.Model.ServiceJobUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ServiceJob.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_service_job(connection, id, service_job_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/service-jobs/#{id}")
      |> add_param(:body, :body, service_job_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ServiceJob},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
