# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Shipping do
  @moduledoc """
  API calls for all endpoints tagged `Shipping`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ShippingCredentials.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_credentials_api(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.ShippingCredentials.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_credentials_api(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/shipping/credentials")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ShippingCredentials},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `rate_request` (RateRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.RateResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_rates_api(Tesla.Env.client, SimpleBillyAPI.Model.RateRequest.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.RateResponse.t} | {:error, Tesla.Env.t}
  def get_rates_api(connection, rate_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/shipping/rates")
      |> add_param(:body, :body, rate_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.RateResponse},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%ProviderInfo{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_providers_api(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.ProviderInfo.t]} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def list_providers_api(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/shipping/providers")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ProviderInfo},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `shipping_credentials` (ShippingCredentials): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ShippingCredentials.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec save_credentials_api(Tesla.Env.client, SimpleBillyAPI.Model.ShippingCredentials.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ShippingCredentials.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def save_credentials_api(connection, shipping_credentials, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/shipping/credentials")
      |> add_param(:body, :body, shipping_credentials)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ShippingCredentials},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
