# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.ShippingThreshold do
  @moduledoc """
  API calls for all endpoints tagged `ShippingThreshold`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `shipping_threshold_create` (ShippingThresholdCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ShippingThreshold.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_shipping_threshold(Tesla.Env.client, SimpleBillyAPI.Model.ShippingThresholdCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.ShippingThreshold.t} | {:error, Tesla.Env.t}
  def create_shipping_threshold(connection, shipping_threshold_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/shipping-thresholds")
      |> add_param(:body, :body, shipping_threshold_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.ShippingThreshold},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `threshold_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_shipping_threshold(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_shipping_threshold(connection, threshold_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/shipping-thresholds/#{threshold_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `product_id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:warehouseId` (String.t): 

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.DeliverableResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_deliverable(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.DeliverableResponse.t} | {:error, Tesla.Env.t}
  def get_deliverable(connection, product_id, opts \\ []) do
    optional_params = %{
      :warehouseId => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/shipping-thresholds/deliverable")
      |> add_param(:query, :productId, product_id)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.DeliverableResponse},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `threshold_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ShippingThreshold.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_shipping_threshold(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.ShippingThreshold.t} | {:error, Tesla.Env.t}
  def get_shipping_threshold(connection, threshold_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/shipping-thresholds/#{threshold_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ShippingThreshold},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:product_id` (String.t): 
    - `:warehouse_id` (String.t): 
    - `:is_active` (boolean()): 

  ### Returns

  - `{:ok, [%ShippingThreshold{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_shipping_thresholds(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.ShippingThreshold.t]} | {:error, Tesla.Env.t}
  def list_shipping_thresholds(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :product_id => :query,
      :warehouse_id => :query,
      :is_active => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/shipping-thresholds/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ShippingThreshold},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `threshold_id` (String.t): 
  - `shipping_threshold_update` (ShippingThresholdUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ShippingThreshold.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_shipping_threshold(Tesla.Env.client, String.t, SimpleBillyAPI.Model.ShippingThresholdUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.ShippingThreshold.t} | {:error, Tesla.Env.t}
  def update_shipping_threshold(connection, threshold_id, shipping_threshold_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/shipping-thresholds/#{threshold_id}")
      |> add_param(:body, :body, shipping_threshold_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ShippingThreshold},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
