# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.StockMovement do
  @moduledoc """
  API calls for all endpoints tagged `StockMovement`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `movement_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.StockMovement.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_stock_movement(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.StockMovement.t} | {:error, Tesla.Env.t}
  def get_stock_movement(connection, movement_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/stock-movements/#{movement_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.StockMovement},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:pageSize` (integer()): 
    - `:productId` (String.t): 
    - `:warehouseId` (String.t): 
    - `:movementType` (String.t): 
    - `:from` (Date.t): Only movements on or after this date (inclusive).
    - `:to` (Date.t): Only movements on or before this date (inclusive).

  ### Returns

  - `{:ok, [%StockMovement{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_stock_movements(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.StockMovement.t]} | {:error, Tesla.Env.t}
  def list_stock_movements(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :pageSize => :query,
      :productId => :query,
      :warehouseId => :query,
      :movementType => :query,
      :from => :query,
      :to => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/stock-movements/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.StockMovement},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
