# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.StockTransfer do
  @moduledoc """
  API calls for all endpoints tagged `StockTransfer`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `stock_transfer` (StockTransfer): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.StockTransfer.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_stock_transfer(Tesla.Env.client, SimpleBillyAPI.Model.StockTransfer.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.StockTransfer.t} | {:error, Tesla.Env.t}
  def create_stock_transfer(connection, stock_transfer, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/stock-transfers")
      |> add_param(:body, :body, stock_transfer)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.StockTransfer},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `stock_transfer_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_stock_transfer(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_stock_transfer(connection, stock_transfer_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/stock-transfers/#{stock_transfer_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `stock_transfer_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.StockTransfer.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_stock_transfer(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.StockTransfer.t} | {:error, Tesla.Env.t}
  def get_stock_transfer(connection, stock_transfer_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/stock-transfers/#{stock_transfer_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.StockTransfer},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:status` (String.t): 
    - `:warehouse_id` (String.t): 

  ### Returns

  - `{:ok, [%StockTransfer{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_stock_transfers(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.StockTransfer.t]} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def list_stock_transfers(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :status => :query,
      :warehouse_id => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/stock-transfers/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.StockTransfer},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `stock_transfer_id` (String.t): 
  - `stock_transfer_status_update` (StockTransferStatusUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.StockTransfer.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_stock_transfer_status(Tesla.Env.client, String.t, SimpleBillyAPI.Model.StockTransferStatusUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.StockTransfer.t} | {:error, Tesla.Env.t}
  def update_stock_transfer_status(connection, stock_transfer_id, stock_transfer_status_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/stock-transfers/#{stock_transfer_id}/status")
      |> add_param(:body, :body, stock_transfer_status_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.StockTransfer},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
