# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.SupplierCondition do
  @moduledoc """
  API calls for all endpoints tagged `SupplierCondition`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `supplier_condition_create` (SupplierConditionCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.SupplierCondition.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_supplier_condition(Tesla.Env.client, SimpleBillyAPI.Model.SupplierConditionCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.SupplierCondition.t} | {:error, Tesla.Env.t}
  def create_supplier_condition(connection, supplier_condition_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/supplier-conditions")
      |> add_param(:body, :body, supplier_condition_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.SupplierCondition},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `supplier_condition_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_supplier_condition(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_supplier_condition(connection, supplier_condition_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/supplier-conditions/#{supplier_condition_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `supplier_condition_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.SupplierCondition.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_supplier_condition(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.SupplierCondition.t} | {:error, Tesla.Env.t}
  def get_supplier_condition(connection, supplier_condition_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/supplier-conditions/#{supplier_condition_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.SupplierCondition},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): 
    - `:page_size` (integer()): 
    - `:supplier_contact_id` (String.t): 
    - `:search` (String.t): 

  ### Returns

  - `{:ok, [%SupplierCondition{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_supplier_conditions(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.SupplierCondition.t]} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def list_supplier_conditions(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :supplier_contact_id => :query,
      :search => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/supplier-conditions/")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.SupplierCondition},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `supplier_condition_id` (String.t): 
  - `supplier_condition_update` (SupplierConditionUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.SupplierCondition.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_supplier_condition(Tesla.Env.client, String.t, SimpleBillyAPI.Model.SupplierConditionUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.SupplierCondition.t} | {:error, Tesla.Env.t}
  def update_supplier_condition(connection, supplier_condition_id, supplier_condition_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/supplier-conditions/#{supplier_condition_id}")
      |> add_param(:body, :body, supplier_condition_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.SupplierCondition},
      {400, SimpleBillyAPI.Model.PluginError},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
