# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.SupportTicket do
  @moduledoc """
  API calls for all endpoints tagged `SupportTicket`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `create_ticket_request` (CreateTicketRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.SupportTicket.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_ticket_api(Tesla.Env.client, SimpleBillyAPI.Model.CreateTicketRequest.t, keyword()) :: {:ok, SimpleBillyAPI.Model.SupportTicket.t} | {:error, Tesla.Env.t}
  def create_ticket_api(connection, create_ticket_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/support/tickets")
      |> add_param(:body, :body, create_ticket_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.SupportTicket}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `ticket_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_ticket_api(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def delete_ticket_api(connection, ticket_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/support/tickets/#{ticket_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `ticket_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.SupportTicket.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_ticket_api(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.SupportTicket.t} | {:error, Tesla.Env.t}
  def get_ticket_api(connection, ticket_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/support/tickets/#{ticket_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.SupportTicket}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:status` (String.t): 
    - `:priority` (String.t): 
    - `:assigned_to` (String.t): 
    - `:channel_type` (String.t): 
    - `:customer_id` (String.t): 
    - `:search` (String.t): 
    - `:page` (integer()): 
    - `:page_size` (integer()): 

  ### Returns

  - `{:ok, [%SupportTicket{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_tickets_api(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.SupportTicket.t]} | {:error, Tesla.Env.t}
  def list_tickets_api(connection, opts \\ []) do
    optional_params = %{
      :status => :query,
      :priority => :query,
      :assigned_to => :query,
      :channel_type => :query,
      :customer_id => :query,
      :search => :query,
      :page => :query,
      :page_size => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/support/tickets")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.SupportTicket}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `ticket_id` (String.t): 
  - `support_ticket_update` (SupportTicketUpdate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.SupportTicket.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_ticket_api(Tesla.Env.client, String.t, SimpleBillyAPI.Model.SupportTicketUpdate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.SupportTicket.t} | {:error, Tesla.Env.t}
  def update_ticket_api(connection, ticket_id, support_ticket_update, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/support/tickets/#{ticket_id}")
      |> add_param(:body, :body, support_ticket_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.SupportTicket}
    ])
  end
end
