# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.SupportChannel do
  @moduledoc """
  API calls for all endpoints tagged `SupportChannel`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `create_channel_dto` (CreateChannelDto): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.SupportChannel.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_channel_api(Tesla.Env.client, SimpleBillyAPI.Model.CreateChannelDto.t, keyword()) :: {:ok, SimpleBillyAPI.Model.SupportChannel.t} | {:error, Tesla.Env.t}
  def create_channel_api(connection, create_channel_dto, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/support/channels")
      |> add_param(:body, :body, create_channel_dto)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.SupportChannel}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `channel_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_channel_api(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def delete_channel_api(connection, channel_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/support/channels/#{channel_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%SupportChannel{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_channels_api(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.SupportChannel.t]} | {:error, Tesla.Env.t}
  def list_channels_api(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/support/channels")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.SupportChannel}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `channel_id` (String.t): 
  - `update_channel_dto` (UpdateChannelDto): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.SupportChannel.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_channel_api(Tesla.Env.client, String.t, SimpleBillyAPI.Model.UpdateChannelDto.t, keyword()) :: {:ok, SimpleBillyAPI.Model.SupportChannel.t} | {:error, Tesla.Env.t}
  def update_channel_api(connection, channel_id, update_channel_dto, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/support/channels/#{channel_id}")
      |> add_param(:body, :body, update_channel_dto)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.SupportChannel}
    ])
  end
end
