# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.TicketMessage do
  @moduledoc """
  API calls for all endpoints tagged `TicketMessage`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `ticket_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%TicketMessage{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_messages_api(Tesla.Env.client, String.t, keyword()) :: {:ok, [SimpleBillyAPI.Model.TicketMessage.t]} | {:error, Tesla.Env.t}
  def list_messages_api(connection, ticket_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/support/tickets/#{ticket_id}/messages")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.TicketMessage}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `ticket_id` (String.t): 
  - `send_message_dto` (SendMessageDto): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.TicketMessage.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec send_message_api(Tesla.Env.client, String.t, SimpleBillyAPI.Model.SendMessageDto.t, keyword()) :: {:ok, SimpleBillyAPI.Model.TicketMessage.t} | {:error, Tesla.Env.t}
  def send_message_api(connection, ticket_id, send_message_dto, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/support/tickets/#{ticket_id}/messages")
      |> add_param(:body, :body, send_message_dto)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.TicketMessage}
    ])
  end
end
