# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Trainings do
  @moduledoc """
  API calls for all endpoints tagged `Trainings`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%MyTrainingItem{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_my_trainings(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.MyTrainingItem.t]} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def get_my_trainings(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/trainings/me")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.MyTrainingItem},
      {404, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `code` (String.t): Training code, e.g. data_privacy
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.TrainingContent.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_training_content(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.TrainingContent.t} | {:error, Tesla.Env.t}
  def get_training_content(connection, code, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/trainings/content/#{code}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.TrainingContent},
      {404, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%HrTrainingOverview{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_training_overview(Tesla.Env.client, keyword()) :: {:ok, [SimpleBillyAPI.Model.HrTrainingOverview.t]} | {:error, Tesla.Env.t}
  def get_training_overview(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/trainings/overview")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.HrTrainingOverview}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `submit_result_dto` (SubmitResultDto): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.SubmitResultResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec submit_training_result(Tesla.Env.client, SimpleBillyAPI.Model.SubmitResultDto.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, SimpleBillyAPI.Model.SubmitResultResponse.t} | {:error, Tesla.Env.t}
  def submit_training_result(connection, submit_result_dto, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/trainings/submit-result")
      |> add_param(:body, :body, submit_result_dto)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.SubmitResultResponse},
      {400, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
