# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.UserManagement do
  @moduledoc """
  API calls for all endpoints tagged `UserManagement`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `user_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.TenantUser.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_user(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.TenantUser.t} | {:error, Tesla.Env.t}
  def get_user(connection, user_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/users/#{user_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.TenantUser},
      {403, false},
      {404, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%TenantUser{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_users(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, [SimpleBillyAPI.Model.TenantUser.t]} | {:error, Tesla.Env.t}
  def list_users(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/users")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.TenantUser},
      {403, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `user_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_user(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def remove_user(connection, user_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/users/#{user_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {403, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `user_id` (String.t): 
  - `update_permissions_payload` (UpdatePermissionsPayload): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_user_permissions(Tesla.Env.client, String.t, SimpleBillyAPI.Model.UpdatePermissionsPayload.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def update_user_permissions(connection, user_id, update_permissions_payload, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/users/#{user_id}/permissions")
      |> add_param(:body, :body, update_permissions_payload)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {403, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `user_id` (String.t): 
  - `update_role_payload` (UpdateRolePayload): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_user_role(Tesla.Env.client, String.t, SimpleBillyAPI.Model.UpdateRolePayload.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def update_user_role(connection, user_id, update_role_payload, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/users/#{user_id}/role")
      |> add_param(:body, :body, update_role_payload)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {403, false}
    ])
  end
end
