# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.User do
  @moduledoc """
  API calls for all endpoints tagged `User`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """
  Change the current user's password (requires the current password).

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `change_password_request` (ChangePasswordRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec change_password(Tesla.Env.client, SimpleBillyAPI.Model.ChangePasswordRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def change_password(connection, change_password_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/user/change-password")
      |> add_param(:body, :body, change_password_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, false}
    ])
  end

  @doc """
  Create a new team within the current tenant

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `team_create` (TeamCreate): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ApiResponseTeam.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_team(Tesla.Env.client, SimpleBillyAPI.Model.TeamCreate.t, keyword()) :: {:ok, SimpleBillyAPI.Model.ApiResponseTeam.t} | {:error, Tesla.Env.t}
  def create_team(connection, team_create, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/user/teams")
      |> add_param(:body, :body, team_create)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ApiResponseTeam}
    ])
  end

  @doc """
  Generate a new API key for the current user

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ApiResponseString.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec generate_api_key(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.ApiResponseString.t} | {:error, Tesla.Env.t}
  def generate_api_key(connection, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/user/api-key")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ApiResponseString}
    ])
  end

  @doc """
  Invite a user to the current tenant/organization

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `invite_request` (InviteRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec invite_user(Tesla.Env.client, SimpleBillyAPI.Model.InviteRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def invite_user(connection, invite_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/user/invite")
      |> add_param(:body, :body, invite_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  List all teams in the current tenant

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ApiResponseVecTeam.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_teams(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.ApiResponseVecTeam.t} | {:error, Tesla.Env.t}
  def list_teams(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/user/teams")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ApiResponseVecTeam}
    ])
  end

  @doc """
  Remove a user from the current organization

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `remove_user_request` (RemoveUserRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_user_from_org(Tesla.Env.client, SimpleBillyAPI.Model.RemoveUserRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def remove_user_from_org(connection, remove_user_request, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/user/remove")
      |> add_param(:body, :body, remove_user_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {401, false}
    ])
  end

  @doc """
  Update the current user's profile

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `update_profile_request` (UpdateProfileRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_profile(Tesla.Env.client, SimpleBillyAPI.Model.UpdateProfileRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def update_profile(connection, update_profile_request, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/user/profile")
      |> add_param(:body, :body, update_profile_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get the current user's profile

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ApiResponseUserProfile.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec user_profile(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.ApiResponseUserProfile.t} | {:error, Tesla.Env.t}
  def user_profile(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/user/profile")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ApiResponseUserProfile},
      {404, false}
    ])
  end

  @doc """
  List all tenants (organizations) the current user belongs to

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.ApiResponseVecUserTenantInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec user_tenants(Tesla.Env.client, keyword()) :: {:ok, SimpleBillyAPI.Model.ApiResponseVecUserTenantInfo.t} | {:error, Tesla.Env.t}
  def user_tenants(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/user/tenants")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.ApiResponseVecUserTenantInfo}
    ])
  end
end
