# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.WarehouseStock do
  @moduledoc """
  API calls for all endpoints tagged `WarehouseStock`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `warehouse_id` (String.t): 
  - `stock_adjustment` (StockAdjustment): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.WarehouseStock.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_warehouse_stock(Tesla.Env.client, String.t, SimpleBillyAPI.Model.StockAdjustment.t, keyword()) :: {:ok, SimpleBillyAPI.Model.WarehouseStock.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def create_warehouse_stock(connection, warehouse_id, stock_adjustment, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/api/v1/warehouses/#{warehouse_id}/stock")
      |> add_param(:body, :body, stock_adjustment)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, SimpleBillyAPI.Model.WarehouseStock},
      {400, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `warehouse_id` (String.t): 
  - `product_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_warehouse_stock(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def delete_warehouse_stock(connection, warehouse_id, product_id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/api/v1/warehouses/#{warehouse_id}/stock/#{product_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `warehouse_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%WarehouseStock{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_warehouse_stock(Tesla.Env.client, String.t, keyword()) :: {:ok, SimpleBillyAPI.Model.PluginError.t} | {:ok, [SimpleBillyAPI.Model.WarehouseStock.t]} | {:error, Tesla.Env.t}
  def list_warehouse_stock(connection, warehouse_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/api/v1/warehouses/#{warehouse_id}/stock")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.WarehouseStock},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `warehouse_id` (String.t): 
  - `product_id` (String.t): 
  - `stock_adjustment` (StockAdjustment): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SimpleBillyAPI.Model.WarehouseStock.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_warehouse_stock(Tesla.Env.client, String.t, String.t, SimpleBillyAPI.Model.StockAdjustment.t, keyword()) :: {:ok, SimpleBillyAPI.Model.WarehouseStock.t} | {:ok, SimpleBillyAPI.Model.PluginError.t} | {:error, Tesla.Env.t}
  def update_warehouse_stock(connection, warehouse_id, product_id, stock_adjustment, _opts \\ []) do
    request =
      %{}
      |> method(:put)
      |> url("/api/v1/warehouses/#{warehouse_id}/stock/#{product_id}")
      |> add_param(:body, :body, stock_adjustment)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, SimpleBillyAPI.Model.WarehouseStock},
      {404, SimpleBillyAPI.Model.PluginError},
      {500, SimpleBillyAPI.Model.PluginError}
    ])
  end
end
