# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SimpleBillyAPI.Api.Zugferd do
  @moduledoc """
  API calls for all endpoints tagged `Zugferd`.
  """

  alias SimpleBillyAPI.Connection
  import SimpleBillyAPI.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (SimpleBillyAPI.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:supplier_name` (String.t): 
    - `:supplier_street` (String.t): 
    - `:supplier_city` (String.t): 
    - `:supplier_zip` (String.t): 
    - `:supplier_country` (String.t): 
    - `:supplier_vat_id` (String.t): 

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec generate_zugferd_api(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def generate_zugferd_api(connection, id, opts \\ []) do
    optional_params = %{
      :supplier_name => :query,
      :supplier_street => :query,
      :supplier_city => :query,
      :supplier_zip => :query,
      :supplier_country => :query,
      :supplier_vat_id => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/api/v1/invoices/#{id}/zugferd")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {404, false},
      {500, false}
    ])
  end
end
